### ISSUE TITLE
Can not find libbrotlicommon when bundling macOS application

### ISSUE THREAD

**Issue by Robot-DaneelOlivaw** [mpv-player/mpv#10063]
### Important Information

- mpv version
master branch
- macOS Version
macOS 12.3.1 (intel)
- Source of the mpv binary or bundle
Self-compiled with default configuration (It doesn't work with Homebrew version either)
- If known which version of mpv introduced the problem
It used to work... a long time ago

### Reproduction steps
```shell
meson build
meson compile -C build
python3 TOOLS/osxbundle.py build/mpv
```

### Expected behavior
A functional app is created

### Actual behavior
Can not find libbrotlicommon

### Log file
```
$ python3 TOOLS/osxbundle.py build/mpv
Creating Mac OS X application bundle (version: 0.34.0-UNKNOWN)...
> copying bundle skeleton
> copying binary
> create bundle symlink
> generating Info.plist
> bundling dependencies
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: @loader_path/libbrotlicommon.1.dylib (No such file or directory)
Traceback (most recent call last):
  File "/Users/R-DO/Developer/mpv/TOOLS/dylib-unhell.py", line 130, in <module>
    main()
  File "/Users/R-DO/Developer/mpv/TOOLS/dylib-unhell.py", line 121, in main
    process_libraries(libs, binary)
  File "/Users/R-DO/Developer/mpv/TOOLS/dylib-unhell.py", line 80, in process_libraries
    shutil.copy(src, dst)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '@loader_path/libbrotlicommon.1.dylib'
>> gathering all linked libraries
>> copying and processing all linked libraries
done.
```

**Comment by eko5624** [comment]
Check https://github.com/mpv-player/mpv/pull/9334

And try this. 

meson build
meson compile -C build
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/usr/local/opt/brotli/lib/libbrotlicommon.1.dylib" /usr/local/opt/brotli/lib/libbrotlidec.1.dylib
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/usr/local/opt/brotli/lib/libbrotlicommon.1.dylib" /usr/local/opt/brotli/lib/libbrotlienc.1.dylib
python3 TOOLS/osxbundle.py build/mpv

**Comment by Robot-DaneelOlivaw** [comment]
@eko5624 That actually worked. Thank you so much!

**Comment by Coeur** [comment]
I had brotli installed from brew, so I had to do:
```
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/opt/homebrew/lib/libbrotlicommon.1.dylib" /opt/homebrew/lib/libbrotlidec.1.dylib
install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/opt/homebrew/lib/libbrotlicommon.1.dylib" /opt/homebrew/lib/libbrotlienc.1.dylib
```
