### ISSUE TITLE
mpv crashes with "SIGSEGV, Segmentation fault" on linux with modesetting driver

### ISSUE THREAD

**Issue by suuuehgi** [mpv-player/mpv#10318]
```bash
> mpv filename.mp4
 (+) Video --vid=1 (*) (h264 3840x2160 25.000fps)
 (+) Audio --aid=1 (*) (aac 1ch 32000Hz)
libEGL warning: DRI2: failed to authenticate
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu] Failed to commit ModeSetting atomic request (-13)
[vo/gpu/opengl] Failed to set CRTC for connector 95: Permission denied
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
AO: [pulse] 32000Hz mono 1ch float
VO: [gpu] 3840x2160 yuv420p
fish: Job 1, 'mpv filename.mp4' terminated by signal SIGSEGV (Address boundary error)
```
gdb backtrace
```log
#0  0x0000000000000000 in  ()
#1  0x00007fff6a8b5a6b in  () at /usr/lib/libnvidia-glcore.so.515.48.07
#2  0x00007fff6a8c5fa8 in  () at /usr/lib/libnvidia-glcore.so.515.48.07
#3  0x00007fffb52a659e in  () at /usr/lib/libGLX_nvidia.so.0
#4  0x00007fffb52a76d8 in  () at /usr/lib/libGLX_nvidia.so.0
#5  0x00007fffb528a08c in  () at /usr/lib/libGLX_nvidia.so.0
#6  0x00007fff6a89dd6a in  () at /usr/lib/libnvidia-glcore.so.515.48.07
#7  0x00007fffb5250107 in  () at /usr/lib/libGLX_nvidia.so.0
#8  0x00007fff6abf0283 in  () at /usr/lib/libnvidia-glcore.so.515.48.07
#9  0x00007fff6abf0818 in  () at /usr/lib/libnvidia-glcore.so.515.48.07
#10 0x00007fff6abf334e in  () at /usr/lib/libnvidia-glcore.so.515.48.07
#11 0x00007fff6abe7327 in  () at /usr/lib/libnvidia-glcore.so.515.48.07
#12 0x00007fff6abf2ddf in  () at /usr/lib/libnvidia-glcore.so.515.48.07
#13 0x00007fffb52a4aef in  () at /usr/lib/libGLX_nvidia.so.0
#14 0x00007ffff51c7581 in  () at /usr/lib/libvulkan.so.1
#15 0x00007ffff5a9d80b in  () at /usr/lib/libplacebo.so.192
#16 0x00007ffff5a9e22e in  () at /usr/lib/libplacebo.so.192
#17 0x00007ffff5a7f315 in pl_swapchain_resize () at /usr/lib/libplacebo.so.192
#18 0x0000555555692ca4 in  ()
#19 0x0000555555686a5d in  ()
#20 0x0000555555682b4e in  ()
#21 0x00005555555e4ac8 in  ()
#22 0x00005555556879ed in  ()
#23 0x00007ffff4c8c54d in  () at /usr/lib/libc.so.6
#24 0x00007ffff4d11874 in clone () at /usr/lib/libc.so.6
```
Versions
```bash
> mpv --version
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0.1

> uname -a
Linux hostname 5.18.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 16 Jun 2022 20:40:45 +0000 x86_64 GNU/Linux
```
Xorg log
```log
[...]
[    22.154] (II) LoadModule: "modesetting"
[    22.155] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[    22.158] (II) Module modesetting: vendor="X.Org Foundation"
[    22.158]    compiled for 1.21.1.3, module version = 1.21.1
[    22.158]    Module class: X.Org Video Driver
[    22.158]    ABI class: X.Org Video Driver, version 25.2
[    22.158] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[...]
```

**Comment by sfan5** [comment]
Provide a full log as written in the instructions.
