### ISSUE TITLE
mpv crashes on ogg files after 758f8f7

### ISSUE THREAD

**Issue by bugmen0t** [mpv-player/mpv#1040]
Locally reverting the commit helps.
```
$ pkg info -x ffmpeg ogg vorbis
ffmpeg-2.2.4_1,1
libogg-1.3.2,4
libvorbis-1.3.4_1,3
```
```
(gdb) r
Starting program: build/mpv --really-quiet --no-config http://hpr.dogphilosophy.net/test/ogg.ogg
[New LWP 100700]
[New Thread 813c06400 (LWP 100700)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 813c06400 (LWP 100700)]
0x00000008060e2dee in __je_arena_mapbitsp_get (chunk=<optimized out>, pageind=<optimized out>, chunk=<optimized out>, pageind=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/arena.h:518
518             return (&arena_mapp_get(chunk, pageind)->bits);
(gdb) bt
#0  0x00000008060e2dee in __je_arena_mapbitsp_get (chunk=<optimized out>, pageind=<optimized out>, chunk=<optimized out>, pageind=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/arena.h:518
#1  __je_arena_mapbits_get (chunk=<optimized out>, pageind=<optimized out>, chunk=<optimized out>, pageind=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/arena.h:532
#2  __je_arena_mapbits_binind_get (chunk=<optimized out>, pageind=<optimized out>, chunk=<optimized out>, pageind=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/arena.h:573
#3  __je_arena_salloc (demote=<optimized out>, ptr=<optimized out>, demote=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/arena.h:991
#4  __je_isalloc (demote=<optimized out>, ptr=<optimized out>, demote=<optimized out>) at /usr/src/lib/libc/../../contrib/jemalloc/include/jemalloc/internal/jemalloc_internal.h:849
#5  ifree (ptr=0xffffffff) at jemalloc_jemalloc.c:1233
#6  0x00000008060e3169 in __free (ptr=0xffffffff) at jemalloc_jemalloc.c:1313
#7  0x0000000800c36305 in av_free (ptr=0xffffffff) at libavutil/mem.c:231
#8  0x00000008010e90de in av_packet_free_side_data (pkt=0x816c18100) at libavcodec/avpacket.c:275
#9  0x00000008010ea115 in av_packet_unref (pkt=0x816c18100) at libavcodec/avpacket.c:530
#10 0x00000000004547a1 in packet_destroy (ptr=0x816c18060) at ../demux/packet.c:32
#11 0x0000000000518b86 in ta_free (ptr=0x816c18060) at ../ta/ta.c:259
#12 0x00000000004119bd in decode_packet (da=0x813cdb4c0) at ../audio/decode/ad_lavc.c:336
#13 0x0000000000412edc in initial_audio_decode (da=0x813cdb4c0) at ../audio/decode/dec_audio.c:227
#14 0x0000000000475af9 in fill_audio_out_buffers (mpctx=0x813c66840, endpts=-9.2233720368547758e+18) at ../player/audio.c:367
#15 0x000000000049ab5d in run_playloop (mpctx=0x813c66840) at ../player/playloop.c:847
#16 0x000000000048f47e in play_current_file (mpctx=0x813c66840) at ../player/loadfile.c:1299
#17 0x000000000048e0ed in mp_play_files (mpctx=0x813c66840) at ../player/loadfile.c:1431
#18 0x000000000049209f in mpv_main (argc=4, argv=0x7fffffffe418) at ../player/main.c:531
#19 0x000000000051ab62 in main (argc=4, argv=0x7fffffffe418) at ../player/main_fn.c:13
(gdb) f 12
#12 0x00000000004119bd in decode_packet (da=0x813cdb4c0) at ../audio/decode/ad_lavc.c:336
336                 talloc_free(mpkt);
(gdb) i loc
priv = 0x813c1fc40
avctx = 0x813d9f600
mpkt = 0x816c18060
in_len = 75
pkt = {
  buf = 0x816c0e060,
  pts = -4655076699637226843,
  dts = -4655076699637226843,
  data = 0x813c9fd60 "l)y",
  size = 75,
  stream_index = 0,
  flags = 1,
  side_data = 0x816c0e040,
  side_data_elems = 2,
  duration = 0,
  destruct = 0x0,
  priv = 0x0,
  pos = -1,
  convergence_duration = 0
}
got_frame = 0
ret = 75
out_pts = 1.713999771896164e-313
(gdb) p *mpkt
$1 = {
  len = 0,
  pts = -9.2233720368547758e+18,
  dts = -0.0026666666666666666,
  duration = 0.0026666666666666666,
  pos = 4533,
  buffer = 0x813c9fdab "",
  keyframe = true,
  stream = 0,
  next = 0x0,
  avpacket = 0x816c18100
}
```

**Comment by rrooij** [comment]
This issue should be closed, since it was already solved by updating ffmpeg.

**Comment by wm4** [comment]
Well ok. I never found out what's wrong with it.
