### ISSUE TITLE
mpv crashes due to segfault (musl + hardened malloc)

### ISSUE THREAD

**Issue by notmentaloutlaw** [mpv-player/mpv#11890]
### Important Information
mpv version: 0.35.1
OS: gentoo (hardened/musl/selinux) + libhardened malloc as the memory allocator
Source: from the ::gentoo repos
WM: Hyprland 0.26.0

### Reproduction steps

Try open a video file using mpv file.mkv and you will obtain the segmentation fault. It is probably due to hardened malloc as using LD_PRELOAD="" mpv file.mkv works fine on musl.

I have posted the gdb backtrace here:

```
gdb --args /usr/bin/mpv 04.mkv 
GNU gdb (Gentoo 13.2 vanilla) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-gentoo-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/mpv...
Reading symbols from /usr/lib/debug//usr/bin/mpv.debug...
(gdb) run
Starting program: /usr/bin/mpv 04.mkv
[New LWP 29016]
[New LWP 29017]
[New LWP 29018]
[New LWP 29019]
[New LWP 29020]
[New LWP 29021]
[New LWP 29022]
[New LWP 29023]
[New LWP 29024]
[osc_on_seek] res value " function: 0x79b41f85da80 " function 
[LWP 29021 exited]
[osc_on_seek] found function: 0x79b41f85da80 nil 
[New LWP 29025]
[LWP 29025 exited]
[New LWP 29026]
[New LWP 29027]
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 44100Hz)
 (+) Subs  --sid=1 --slang=eng (*) 'English subs' (ass)
[New LWP 29028]
[New LWP 29029]
[New LWP 29030]
[New LWP 29031]
[New LWP 29032]
[New LWP 29033]
[New LWP 29034]
[New LWP 29035]
[New LWP 29036]
[New LWP 29037]
[New LWP 29038]
[New LWP 29039]
[New LWP 29040]
Using hardware decoding (vaapi).
[New LWP 29043]
[New LWP 29044]
AO: [pipewire] 44100Hz stereo 2ch floatp
VO: [gpu] 1920x1080 vaapi[nv12]

Thread 20 "mpv:gl0" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 29034]
0x00007ffff7fb6c44 in pthread_mutex_lock () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007ffff7fb6c44 in pthread_mutex_lock () from /lib/ld-musl-x86_64.so.1
#1  0x00007ffff7f37763 in allocate_small () from /usr/local/lib/libhardened_malloc.so
#2  0x00007ffff7f39180 in realloc () from /usr/local/lib/libhardened_malloc.so
#3  0x0000671fa87537e6 in ?? () from /usr/lib/dri/radeonsi_dri.so
#4  0x0000671fa85fa30e in ?? () from /usr/lib/dri/radeonsi_dri.so
#5  0x0000671fa84e9a88 in ?? () from /usr/lib/dri/radeonsi_dri.so
#6  0x0000671fa848a3d1 in ?? () from /usr/lib/dri/radeonsi_dri.so
#7  0x0000671fa84d727b in ?? () from /usr/lib/dri/radeonsi_dri.so
#8  0x00007ffff7fb5cfe in ?? () from /lib/ld-musl-x86_64.so.1
#9  0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by Dudemanguy** [comment]
You're going to need more debug symbols if you want to find out what's actually happening here. Although that backtrace suggests it's in the driver.
