### ISSUE TITLE
Mpv can't play anything

### ISSUE THREAD

**Issue by vincuska** [mpv-player/mpv#12602]
### Important Information

- mpv version 0.29.1
- Linux Distribution and Version
- Raspbian GNU/Linux 10
- xdg-open 1.1.3
- vcgencmd version 30aa0d70ab280427ba04ebc718c81d4350b9d394

### Reproduction steps

Trying to start any youtube video for example:
mpv --no-video "youtube video link"

### Expected behavior

It should start playing sounds

### Actual behavior

Spits out some error:
```
Playing: "youtube video link"
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "/usr/bin/youtube-dl", line 11, in <module>
[ytdl_hook]     load_entry_point('youtube-dl==2019.1.17', 'console_scripts', 'youtube-dl')()
[ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 477, in main
[ytdl_hook]     _real_main(argv)
[ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/__init__.py", line 467, in _real_main
[ytdl_hook]     retcode = ydl.download(all_urls)
[ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2002, in download
[ytdl_hook]     url, force_generic_extractor=self.params.get('force_generic_extractor', False))
[ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
[ytdl_hook]     ie_result = ie.extract(url)
[ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
[ytdl_hook]     ie_result = self._real_extract(url)
[ytdl_hook]   File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1672, in _real_extract
[ytdl_hook]     token = video_info.get('token') or video_info.get('account_playback_token')
[ytdl_hook] AttributeError: 'NoneType' object has no attribute 'get'
[ytdl_hook] youtube-dl failed: unexpected error ocurred
Failed to recognize file format.


Exiting... (Errors when loading file)
```

### Log file

https://0x0.st/HW7z.txt

**Comment by Dudemanguy** [comment]
Google regularly breaks youtube so you're going to need non-ancient versions of mpv and yt-dlp if you want this to work.

**Comment by vincuska** [comment]
It says they are up to date. What are you talking about?

**Comment by Dudemanguy** [comment]
You are on an ancient version of debian carries only woefully out of date packages. The current mpv release is 0.36. youtube-dl is basically abandonware. We can't help you.
