### ISSUE TITLE
Segmentation fault on wayland with force-window=immediate and a YouTube url

### ISSUE THREAD

**Issue by christoph-heinrich** [mpv-player/mpv#13887]
### Important Information

Provide following Information:
- current git master (919a042833202817492d1744e087836b6b02f63f)
- Arch linux
- compiled from source
- introduced by 895f40e150d4bf2261a96fc2586d75f998d2ac5d
- Plasma 6.0.3 with KWin 6.0.3.1
- AMD Radeon R9 380

### Reproduction steps

Run `mpv --no-config --gpu-context=wayland --force-window=immediate "https://www.youtube.com/watch?v=xCBrtopAG80"`

### Expected behavior

Video starts playing

### Actual behavior

Segmentation fault

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/14978615/log.txt)

**Comment by llyyr** [comment]
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==17561==ERROR: AddressSanitizer: SEGV on unknown address 0x0043ffff8078 (pc 0x55ad1b117a77 bp 0x7efdeeb1d270 sp 0x7efdeeb1ca00 T14)
==17561==The signal is caused by a READ memory access.
    #0 0x55ad1b117a77 in QuickCheckForUnpoisonedRegion /home/abuild/rpmbuild/BUILD/llvm-18.1.2.src/projects/compiler-rt/lib/asan/asan_interceptors_memintrinsics.h:37:7
    #1 0x55ad1b117a77 in printf_common(void*, char const*, __va_list_tag*) /home/abuild/rpmbuild/BUILD/llvm-18.1.2.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_format.inc:563:9
    #2 0x55ad1b1196ab in vprintf /home/abuild/rpmbuild/BUILD/llvm-18.1.2.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1644:1
    #3 0x55ad1b1196ab in printf /home/abuild/rpmbuild/BUILD/llvm-18.1.2.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1702:1
    #4 0x55ad1bc9c8f6 in surface_handle_enter /home/llyyr/workspace/mpv/build/../video/out/wayland_common.c:956:5
    #5 0x7efe020f0971  (/lib64/libffi.so.8+0x7971) (BuildId: 1705b3e1a779410b45f989f86e18413d0d2f8cbb)
    #6 0x7efe020ed2de  (/lib64/libffi.so.8+0x42de) (BuildId: 1705b3e1a779410b45f989f86e18413d0d2f8cbb)
    #7 0x7efe020eff35 in ffi_call (/lib64/libffi.so.8+0x6f35) (BuildId: 1705b3e1a779410b45f989f86e18413d0d2f8cbb)
    #8 0x7efe03f14a22  (/lib64/libwayland-client.so.0+0x7a22) (BuildId: f260941ad37b702350342c4d696de83ad7959db7)
    #9 0x7efe03f15202  (/lib64/libwayland-client.so.0+0x8202) (BuildId: f260941ad37b702350342c4d696de83ad7959db7)
    #10 0x7efe03f15493 in wl_display_dispatch_queue_pending (/lib64/libwayland-client.so.0+0x8493) (BuildId: f260941ad37b702350342c4d696de83ad7959db7)
    #11 0x55ad1bc9488e in wayland_dispatch_events /home/llyyr/workspace/mpv/build/../video/out/wayland_common.c:2290:5
    #12 0x55ad1bc9314a in vo_wayland_wait_frame /home/llyyr/workspace/mpv/build/../video/out/wayland_common.c:2908:9
    #13 0x55ad1bdba57a in wayland_vk_swap_buffers /home/llyyr/workspace/mpv/build/../video/out/vulkan/context_wayland.c:40:9
    #14 0x55ad1bdb6ff5 in swap_buffers /home/llyyr/workspace/mpv/build/../video/out/vulkan/context.c:345:9
    #15 0x55ad1baf3238 in flip_page /home/llyyr/workspace/mpv/build/../video/out/vo_gpu_next.c:1175:5
    #16 0x55ad1ba52ce2 in do_redraw /home/llyyr/workspace/mpv/build/../video/out/vo.c:1064:5
    #17 0x55ad1ba494ab in vo_thread /home/llyyr/workspace/mpv/build/../video/out/vo.c:1145:13
    #18 0x55ad1b18d246 in asan_thread_start(void*) /home/abuild/rpmbuild/BUILD/llvm-18.1.2.src/projects/compiler-rt/lib/asan/asan_interceptors.cpp:239:28
    #19 0x7efe03a92bb1 in start_thread (/lib64/libc.so.6+0x92bb1) (BuildId: 07453469054b134d7f4829e267d0ac7b8a725ebc)
    #20 0x7efe03b1400b in __GI___clone3 (/lib64/libc.so.6+0x11400b) (BuildId: 07453469054b134d7f4829e267d0ac7b8a725ebc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/llyyr/workspace/mpv/build/../video/out/wayland_common.c:956:5 in surface_handle_enter
Thread T14 created by T0 here:
    #0 0x55ad1b174a44 in pthread_create /home/abuild/rpmbuild/BUILD/llvm-18.1.2.src/projects/compiler-rt/lib/asan/asan_interceptors.cpp:250:3
    #1 0x55ad1ba38b33 in vo_create /home/llyyr/workspace/mpv/build/../video/out/vo.c:317:9
    #2 0x55ad1ba36d91 in init_best_video_out /home/llyyr/workspace/mpv/build/../video/out/vo.c:342:18
    #3 0x55ad1b75e355 in handle_force_window /home/llyyr/workspace/mpv/build/../player/playloop.c:1019:28
    #4 0x55ad1b737713 in mp_initialize /home/llyyr/workspace/mpv/build/../player/main.c:409:32
    #5 0x55ad1b738560 in mpv_main /home/llyyr/workspace/mpv/build/../player/main.c:430:13
    #6 0x55ad1be27e69 in main /home/llyyr/workspace/mpv/build/../osdep/main-fn-unix.c:5:12
    #7 0x7efe03a2a1ef in __libc_start_call_main (/lib64/libc.so.6+0x2a1ef) (BuildId: 07453469054b134d7f4829e267d0ac7b8a725ebc)

==17561==ABORTING
```

Fixed by #13888
