### ISSUE TITLE
I can't foreground or background mpv from terminal after suspending it with Ctrl-Z

### ISSUE THREAD

**Issue by walterigle** [mpv-player/mpv#14355]
### mpv Information

```bash
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jun  6 2024 18:51:45
libplacebo version: v6.338.2
FFmpeg version: 4.4.4
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
```

### Important Information

- Platform version: OpenBSD current
- GPU model, driver and version: Intel 82Q965 Video
- Source:
- Introduced in version: 0.38.0

### Reproduction Steps

 - Play something from the terminal
 - Press Ctrl-Z
 - Execute bg
 - Execute fg

The more similar issue I found reported is the one described in this
report in 2020:

  https://github.com/mpv-player/mpv/issues/8120

Except for in my case pressing Enter doesn't work, I have to kill the
process.

It doesn't happen with mpv 0.38.0 under Debian testing, nor with mpv
0.37 under Freebsd 14.1.  So far this only happens on OpenBSD.

### Expected Behavior

mpv should leave the suspended state.

### Actual Behavior

mpv stays in suspended state.

### Log File

[output.txt](https://github.com/user-attachments/files/15839697/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
Can't reproduce on Linux.

**Comment by walterigle** [comment]
On Fri, Jun 14, 2024 at 08:10:14AM -0700, Guido Cella wrote:
> Can't reproduce on Linux.

As I said in my report.  Nor under FreeBSD with mpv 0.37 version.


> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/mpv-player/mpv/issues/14355#issuecomment-2168242261
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
Walter

**Comment by walterigle** [comment]
On Fri, Jun 14, 2024 at 08:10:14AM -0700, Guido Cella wrote:
> Can't reproduce on Linux.

In case you assume this is an OpenBSD issue, please note that this is
the only application I experience this issue with (and I already
mentioned the issue at ***@***.***).

> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/mpv-player/mpv/issues/14355#issuecomment-2168242261
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
Walter

**Comment by guidocella** [comment]
Probably caused by something in b75b56f910. But none of the developers use BSD.

**Comment by walterigle** [comment]
I forgot to mention that, as a workaround, I use this setting in mpv.conf:

    profile=builtin-pseudo-gui

With that the problem desapears.

**Comment by walterigle** [comment]
> Probably caused by something in [b75b56f](https://github.com/mpv-player/mpv/commit/b75b56f91048f0ca8f663b93a92aa059787022ce). But none of the developers use BSD.

Today I downloaded and compiled mpv 0.38.0 from source.  Painfully (since I didn't find a way of downloading the diff from github) I reverted the diff from the b75b56f commit you pointed me out.  Well, you nailed it, that's the change that introduced the regression.  Without those changes the issue disappears.

**Comment by N-R-K** [comment]
> @N-R-K: Do you want to take a look into it?

Sure, I'll look at it. But it may take me a bit.

In the meanwhile, if you (@walterigle) can use gdb to step through what's going on in `terminal_thread()` when you press ctrl+z, that would help out a lot since I don't use openbsd myself.

**Comment by walterigle** [comment]
> > @N-R-K: Do you want to take a look into it?
> 
> Sure, I'll look at it. But it may take me a bit.
> 
> In the meanwhile, if you (@walterigle) can use gdb to step through what's going on in `osdep/terminal-unix.c::terminal_thread()` when you press ctrl+z, that would help out a lot since I don't use openbsd myself.

**Comment by walterigle** [comment]
> > @N-R-K: Do you want to take a look into it?
> 
> Sure, I'll look at it. But it may take me a bit.
> 
> In the meanwhile, if you (@walterigle) can use gdb to step through what's going on in `osdep/terminal-unix.c::terminal_thread()` when you press ctrl+z, that would help out a lot since I don't use openbsd myself.



I've used gdb very rarely against core files, asked by some developer in
a report bug.  Tell me if what I did below is useful.  I run the program
under gdb, then I suspended with Ctrl-Z and the run fg twice.

If I did it wrong tell me which command should I use, please.



$ gdb ~/Desktop/mpv-0.38.0/build/mpv
[...]
This GDB was configured as "amd64-unknown-openbsd7.5"...
(gdb) run --no-config ~/Videos/video.mp4 
Starting program: ~/Desktop/mpv-0.38.0/build/mpv --no-config ~/Videos/video.mp4
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/libexec/ld.so]
 (+) Video --vid=1 (*) (h264 640x480 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/libexec/ld.so]
Error while reading shared library symbols:
[...] (same message repeated several times)
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/libexec/ld.so]
[vo/gpu] Disabling scaler #0 lanczos (GLSL version too old).
[vo/gpu] Disabling scaler #1 hermite (GLSL version too old).
[vo/gpu] Disabling linear/sigmoid scaling (GLSL version too old).
[vo/gpu] correct-downscaling requires non-bilinear scaler.
AO: [sndio] 48000Hz stereo 2ch s16
VO: [gpu] 640x480 yuv420p
Error while reading shared library symbols:
Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/libexec/ld.so]
[...] (same message repeated several times)
AV: 00:00:01 / 00:04:52 (0%) A-V: -0.001 
Program received signal SIGTSTP, Stopped (user).
[Switching to thread 561222]
_thread_sys_poll () at /tmp/-:2
2       /tmp/-: No such file or directory.
        in /tmp/-
Current language:  auto; currently asm
(gdb) fg
Continuing.

Program received signal SIGTSTP, Stopped (user).
_thread_sys_poll () at /tmp/-:2
2       in /tmp/-
(gdb) fg
Continuing.

Program received signal SIGTSTP, Stopped (user).
[Switching to thread 163324]
0x00000100166fec67 in av_mallocz () from /usr/local/lib/libavutil.so.15.0
(gdb) fg
Continuing.

Program received signal SIGTSTP, Stopped (user).
[Switching to thread 160557]
futex () at /tmp/-:2
2       /tmp/-: No such file or directory.
        in /tmp/-
(gdb) fg
Continuing.

Program received signal SIGTSTP, Stopped (user).
futex () at /tmp/-:2
2       in /tmp/-
(gdb)

**Comment by walterigle** [comment]
I accidentally closed the issue.  Guys, wouldn't be easier to use a mailing list?

**Comment by avih** [comment]
> Guys, wouldn't be easier to use a mailing list?

To some for sure, but for many it would become much less accessible.

Anyway, it is what it is... and it's not too hard to click the "reopen" button either ;)

**Comment by walterigle** [comment]
Let's see if now I got what N-R-K asked me:

(gdb) bt
#0  _thread_sys_poll () at /tmp/-:2
#1  0x613eec4373e1d889 in ?? ()
#2  0x0000040d55a06632 in _libc_poll_cancel (fds=Variable "fds" is not available.
)
    at /usr/src/lib/libc/sys/w_poll.c:27
#3  0x0000040af7107838 in terminal_thread () at ../osdep/terminal-unix.c:417
#4  0x0000040d504fcc42 in _rthread_start (v=Unhandled dwarf expression opcode 0xa3
)
    at /usr/src/lib/librthread/rthread.c:96
#5  0x0000040d55a3d17a in __tfork_thread ()
    at /usr/src/lib/libc/arch/amd64/sys/tfork_thread.S:87
#6  0x0000040d55a3d17a in __tfork_thread ()
    at /usr/src/lib/libc/arch/amd64/sys/tfork_thread.S:87
Previous frame identical to this frame (corrupt stack?)
(gdb)

**Comment by N-R-K** [comment]
I think gdb was not a good suggestion. What I really wanted was some overview of what the hell is going on. Here's a quick and dirty patch that adds some logging (untested, not sure if it even compiles):

```diff
diff --git a/osdep/terminal-unix.c b/osdep/terminal-unix.c
index 6f7054887..892570b68 100644
--- a/osdep/terminal-unix.c
+++ b/osdep/terminal-unix.c
@@ -437,6 +437,8 @@ static void quit_request_sighandler(int signum)
     errno = saved_errno;
 }
 
+#define LOG(MSG) (fprintf(stderr, "%d: " MSG "\n", __LINE__), fflush(stderr))
+
 static MP_THREAD_VOID terminal_thread(void *ptr)
 {
     mp_thread_set_name("terminal/input");
@@ -461,13 +463,16 @@ static MP_THREAD_VOID terminal_thread(void *ptr)
         bool is_fg = tcgetpgrp(tty_in) == getpgrp();
         int r = polldev(fds, stdin_ok && is_fg ? 3 : 2, buf.len ? ESC_TIMEOUT : INPUT_TIMEOUT);
         if (fds[0].revents) {
+            LOG("got death pipe activity");
             do_deactivate_getch2();
             break;
         }
         if (fds[1].revents & POLLIN) {
+            LOG("got stop/cont pipe activity");
             int8_t c = -1;
             (void)read(stop_cont_pipe[0], &c, 1);
             if (c == PIPE_STOP) {
+                LOG("stopping");
                 do_deactivate_getch2();
                 if (isatty(STDERR_FILENO)) {
                     (void)write(STDERR_FILENO, TERM_ESC_RESTORE_CURSOR,
@@ -479,13 +484,16 @@ static MP_THREAD_VOID terminal_thread(void *ptr)
                 // effectively the same thing.
                 raise(SIGSTOP);
             } else if (c == PIPE_CONT) {
+                LOG("continuing");
                 getch2_poll();
             }
         }
         if (fds[2].revents) {
             int retval = read(tty_in, &buf.b[buf.len], BUF_LEN - buf.len);
-            if (!retval || (retval == -1 && errno != EINTR && errno != EAGAIN && errno != EIO))
+            if (!retval || (retval == -1 && errno != EINTR && errno != EAGAIN && errno != EIO)) {
+                LOG("breaking out");
                 break; // EOF/closed
+            }
             if (retval > 0) {
                 buf.len += retval;
                 process_input(input_ctx, false);
```

Not sure if it will reveal anything interesting or not, but worth a shot.

**Comment by walterigle** [comment]
Hi NRK,
 
On Thu, Jun 27, 2024 at 10:37:45AM -0700, NRK wrote:
> I think gdb was not a good suggestion.  What I really wanted was some
> overview of what the hell is going on.  Here's a quick and dirty patch
> that adds some logging (untested, not sure if it even compiles):

I compiled mpv with your diff, I ran it, press Ctrl-Z and then tried to
fg.  This is the output.

~/mpv-0.38.0$ build/mpv --no-config ~/Videos/video.mp4
 (+) Video --vid=1 (*) (h264 640x480 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[vo/gpu] Disabling scaler #0 lanczos (GLSL version too old).
[vo/gpu] Disabling scaler #1 hermite (GLSL version too old).
[vo/gpu] Disabling linear/sigmoid scaling (GLSL version too old).
[vo/gpu] correct-downscaling requires non-bilinear scaler.
AO: [sndio] 48000Hz stereo 2ch s16
VO: [gpu] 640x480 yuv420p
AV: 00:00:00 / 00:04:52 (0%) A-V: -0.002426: got stop/cont pipe activity
AV: 00:00:01 / 00:04:52 (0%) A-V: -0.001430: stopping
[1] + Suspended (signal)   build/mpv --no-config ~/Videos/video.mp4
~/Desktop/mpv-0.38.0[1]$ fg
build/mpv --no-config ~/Videos/video.mp4
426: got stop/cont pipe activity
430: stopping
[1] + Suspended (signal)   build/mpv --no-config ~/Videos/video.mp4


> [...]
> 
> Not sure if it will reveal anything interesting or not, but worth a shot.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/mpv-player/mpv/issues/14355#issuecomment-2195291060
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***>

-- 
Walter

**Comment by brad0** [comment]
@N-R-K I can give you access to a VM if you want to test anything out.

**Comment by N-R-K** [comment]
Took some cursory glance at the code and I'm not seeing anything obviously wrong.

> I can give you access to a VM if you want to test anything out.

Thanks for the offer. I already have qemu installed locally. I'll look into installing an openbsd image and setting up a dev environment on it sometime this week.
