### ISSUE TITLE
Segfault with fuzzed file (regression)

### ISSUE THREAD

**Issue by tholin** [mpv-player/mpv#1462]
Commit 3f3e1547 "player: change --display-tags behavior" introduced a regression.

This file now segfaults.
https://www.dropbox.com/s/t26xs3wxovxm5cb/regression.mkv

```
$ gdb --args ~/repository/mpv-build_vanilla_debug/mpv/build/mpv --cache=no --no-config --untimed --no-audio --demuxer-thread=no --vd-lavc-threads=1 --ad-lavc-threads=1 --no-input-terminal --vo null regression.mkv
GNU gdb (Gentoo 7.7.1 p1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/cocobo/repository/mpv-build_vanilla_debug/mpv/build/mpv...done.
(gdb) r
Starting program: /home/cocobo/repository/mpv-build_vanilla_debug/mpv/build/mpv --cache=no --no-config --untimed --no-audio --demuxer-thread=no --vd-lavc-threads=1 --ad-lavc-threads=1 --no-input-terminal --vo null regression.mkv
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffed4e7700 (LWP 31559)]
[New Thread 0x7fffecce6700 (LWP 31560)]
Playing: regression.mkv
[New Thread 0x7fffe7fff700 (LWP 31561)]
[Thread 0x7fffe7fff700 (LWP 31561) exited]
[New Thread 0x7fffe7fff700 (LWP 31562)]
[mkv] Invalid SeekHead entry
[mkv] Invalid EBML length at position 4158
[mkv] Error parsing element Info
[mkv] segment uid invalid length 15
[mkv] Unexpected end of file - partial or corrupt file?
[mkv] Error parsing element Tags
[mkv] Unexpected end of file (no clusters found)
[mkv] Expected element 0x1043a770 not found
[mkv] Expected element 0x1941a469 not found
[Thread 0x7fffe7fff700 (LWP 31562) exited]
 (+) Video --vid=1 '%s' (wmv2)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff200bb47 in __strncasecmp_l_avx () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff200bb47 in __strncasecmp_l_avx () from /lib64/libc.so.6
No symbol table info available.
#1  0x000000000043b7cd in mp_tags_filtered (tparent=0x201e050, tags=0x7fffdc203790, list=0x2024410) at ../common/tags.c:94
        x = 0
        key = 0x2024760 "Artist"
        keylen = 6
        prefix = false
        matchlen = 7
        n = 0
        new = 0x207baf0
#2  0x000000000048f16f in update_demuxer_properties (mpctx=0x201e050) at ../player/loadfile.c:171
        info = 0x0
        prev = 0x7fffffffffff
        n_prev = 32767
        had_output = false
        demuxer = 0x7fffdc202e30
        events = 65535
        tracks = 0x7fffdc202e30
#3  0x000000000049243b in play_current_file (mpctx=0x201e050) at ../player/loadfile.c:1118
        opts = 0x20212b0
        tmp = 0x20575a0
        playback_start = -1e+100
        __PRETTY_FUNCTION__ = "play_current_file"
        stream_flags = 0
        startpos = 0
        nothing_played = false
        end_event = {reason = -10256, error = 32767}
#4  0x0000000000492fc9 in mp_play_files (mpctx=0x201e050) at ../player/loadfile.c:1348
        new_entry = 0x20212b0
#5  0x00000000004943d8 in mpv_main (argc=12, argv=0x7fffffffd988) at ../player/main.c:536
        mpctx = 0x201e050
        opts = 0x20212b0
        verbose_env = 0x0
        r = 0
#6  0x0000000000411dcd in main (argc=12, argv=0x7fffffffd988) at ../player/main_fn.c:13
No locals.
```

**Comment by wm4** [comment]
Not really a regression - it was always broken.
