### ISSUE TITLE
Divide by zero with fuzzed file (vf_scale) 

### ISSUE THREAD

**Issue by tholin** [mpv-player/mpv#1467]
This file cause a divide by zero.
https://www.dropbox.com/s/sd9619y3lo63w9q/fpe_vf_scale.mov

There is also an overlapping memcpy warning with valgrind in ffmpeg.
```
$ gdb --args ~/repository/mpv-build_vanilla_debug/mpv/build/mpv --no-config fpe_vf_scale.mov 
GNU gdb (Gentoo 7.7.1 p1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/cocobo/repository/mpv-build_vanilla_debug/mpv/build/mpv...done.
(gdb) r
Starting program: /home/cocobo/repository/mpv-build_vanilla_debug/mpv/build/mpv --no-config fpe_vf_scale.mov
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffed4e7700 (LWP 25899)]
[New Thread 0x7fffecce6700 (LWP 25900)]
[New Thread 0x7fffe7fff700 (LWP 25901)]
Playing: fpe_vf_scale.mov
[New Thread 0x7fffe77fe700 (LWP 25902)]
[Thread 0x7fffe77fe700 (LWP 25902) exited]
[New Thread 0x7fffe77fe700 (LWP 25903)]
[Thread 0x7fffe77fe700 (LWP 25903) exited]
 (+) Video --vid=1 (*) (qpeg)
[New Thread 0x7fffe77fe700 (LWP 25904)]
[New Thread 0x7fffe6ffd700 (LWP 25905)]
[New Thread 0x7fffdffff700 (LWP 25906)]
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: stream 0, offset 0x5537: partial file
[lavf] error reading packet.
Using conversion filter.

Program received signal SIGFPE, Arithmetic exception.
0x00000000004fa61b in reconfig (vf=0x209aeb0, in=0x209af0c, out=0x209af40) at ../video/filter/vf_scale.c:278
278             d_width = vf->priv->h * d_width / d_height;
(gdb) bt full
#0  0x00000000004fa61b in reconfig (vf=0x209aeb0, in=0x209af0c, out=0x209af40) at ../video/filter/vf_scale.c:278
        width = 316
        height = 11060
        d_width = 316
        d_height = 0
        outfmt = 1059
        best = 1033
        round_w = 0
        round_h = 0
        s_fmt = {id = 257, avformat = 2048, flags = 2048, num_planes = 0 '\000', chroma_xs = 0 '\000', 
          chroma_ys = 0 '\000', align_x = 0 '\000', align_y = 0 '\000', bytes = "\000\000\000\t", 
          bpp = "\004\000\000", plane_bits = -62 '\302', xs = "\321\351rd", 
          ys = "\\l\360", <incomplete sequence \320>}
        d_fmt = {id = -12048, avformat = 32767, flags = 5124710, num_planes = 0 '\000', chroma_xs = 0 '\000', 
          chroma_ys = 0 '\000', align_x = 0 '\000', align_y = -128 '\200', bytes = "\302\b\002", 
          bpp = "\000\000\000\f", plane_bits = -81 '\257', xs = "\t\002\000", ys = "\000\000#\004"}
#1  0x00000000004ee5c5 in vf_reconfig_wrapper (vf=0x209aeb0, p=0x7fffffffd190) at ../video/filter/vf.c:605
        r = 0
#2  0x00000000004ee8ca in vf_reconfig (c=0x208bd90, params=0x7fffffffd580, override_params=0x7fffffffd470)
    at ../video/filter/vf.c:647
        vf = 0x209aeb0
        r = 0
        cur = {imgfmt = IMGFMT_PAL8, w = 316, h = 11060, d_w = 316, d_h = 0, colorspace = MP_CSP_RGB, 
          colorlevels = MP_CSP_LEVELS_PC, primaries = MP_CSP_PRIM_BT_709, chroma_location = MP_CHROMA_AUTO, 
          outputlevels = MP_CSP_LEVELS_AUTO, rotate = 180, stereo_in = MP_STEREO3D_MONO, 
          stereo_out = MP_STEREO3D_MONO}
        unused = '\000' <repeats 59 times>, "\001", '\000' <repeats 507 times>
        failing = 0x0
        loglevel = 32767
#3  0x00000000004e8835 in video_reconfig_filters (d_video=0x208bad0, params=0x7fffffffd580)
    at ../video/decode/dec_video.c:438
        opts = 0x20222b0
        p = {imgfmt = IMGFMT_PAL8, w = 316, h = 11060, d_w = 316, d_h = 0, colorspace = MP_CSP_RGB, 
          colorlevels = MP_CSP_LEVELS_PC, primaries = MP_CSP_PRIM_BT_709, chroma_location = MP_CHROMA_AUTO, 
          outputlevels = MP_CSP_LEVELS_AUTO, rotate = 180, stereo_in = MP_STEREO3D_MONO, 
          stereo_out = MP_STEREO3D_MONO}
        sh = 0x7fffd840fd20
        decoder_aspect = 0.0285714287
        force_aspect = -1
#4  0x00000000004a62af in filter_reconfig (mpctx=0x201f050, probe_only=false) at ../player/video.c:128
        d_video = 0x208bad0
        params = {imgfmt = IMGFMT_PAL8, w = 316, h = 11060, d_w = 316, d_h = 11060, colorspace = MP_CSP_AUTO, 
          colorlevels = MP_CSP_LEVELS_AUTO, primaries = MP_CSP_PRIM_AUTO, chroma_location = MP_CHROMA_AUTO, 
          outputlevels = MP_CSP_LEVELS_AUTO, rotate = 180, stereo_in = MP_STEREO3D_MONO, 
          stereo_out = MP_STEREO3D_MONO}
#5  0x00000000004a72df in video_filter (mpctx=0x201f050, eof=false) at ../player/video.c:454
        d_video = 0x208bad0
        vf = 0x208bd90
        need_vf_reconfig = true
#6  0x00000000004a7461 in video_decode_and_filter (mpctx=0x201f050) at ../player/video.c:495
        d_video = 0x208bad0
        r = 1
        eof = false
#7  0x00000000004a7a1a in video_output_image (mpctx=0x201f050, endpts=-9.2233720368547758e+18)
    at ../player/video.c:608
        img = 0x208bad0
        hrseek = false
        r = 1
#8  0x00000000004a8195 in write_video (mpctx=0x201f050, endpts=-9.2233720368547758e+18) at ../player/video.c:756
        opts = 0x20222b0
        vo = 0x207ccf0
        r = -668979664
        p = {imgfmt = 4294956880, w = 32767, h = 4573280, d_w = 0, d_h = -10416, colorspace = 32767, 
          colorlevels = 5312207, primaries = MP_CSP_PRIM_AUTO, chroma_location = MP_CHROMA_AUTO, 
          outputlevels = 10, rotate = 34065648, stereo_in = MP_STEREO3D_MONO, stereo_out = -10352}
        time_frame = 6.953355807318014e-310
        pts = 4576206
        duration = 8589934592
        diff = 1.6670960648233677e-316
        vpts0 = 0
        vpts1 = 1.6670834167428342e-316
#9  0x000000000049e62f in run_playloop (mpctx=0x201f050) at ../player/playloop.c:917
        opts = 0x20222b0
        endpts = -9.2233720368547758e+18
        end_is_new_segment = false
        prevent_eof = false
#10 0x0000000000493000 in play_current_file (mpctx=0x201f050) at ../player/loadfile.c:1191
        opts = 0x20222b0
        tmp = 0x20585c0
        playback_start = 10.324339
        __PRETTY_FUNCTION__ = "play_current_file"
        stream_flags = 0
        startpos = -9.2233720368547758e+18
        nothing_played = false
        end_event = {reason = -10064, error = 32767}
#11 0x000000000049371a in mp_play_files (mpctx=0x201f050) at ../player/loadfile.c:1348
        new_entry = 0x20222b0
#12 0x0000000000494b29 in mpv_main (argc=3, argv=0x7fffffffda48) at ../player/main.c:536
        mpctx = 0x201f050
        opts = 0x20222b0
        verbose_env = 0x0
        r = 0
#13 0x0000000000411dcd in main (argc=3, argv=0x7fffffffda48) at ../player/main_fn.c:13
No locals.
```
```
Source and destination overlap in memcpy(0x17071080, 0x17071080, 316)
   at 0x4C2DB7C: memcpy@@GLIBC_2.14 (/var/tmp/portage/dev-util/valgrind-3.10.1/work/valgrind-3.10.1/memcheck/../shared/vg_replace_strmem.c:915)
   by 0xDBB86F: qpeg_decode_inter (/ffmpeg/libavcodec/qpeg.c:128)
   by 0xDBC62C: decode_frame (/ffmpeg/libavcodec/qpeg.c:285)
   by 0xE8C3AD: avcodec_decode_video2 (/ffmpeg/libavcodec/utils.c:2364)
   by 0x4EA14A: decode (/mpv/build/../video/decode/vd_lavc.c:625)
   by 0x4EA43A: decode_with_fallback (/mpv/build/../video/decode/vd_lavc.c:678)
   by 0x4E7FE8: video_decode (/mpv/build/../video/decode/dec_video.c:314)
   by 0x4A7123: decode_image (/mpv/build/../player/video.c:399)
   by 0x4A73BF: video_decode_and_filter (/mpv/build/../player/video.c:487)
   by 0x4A7A19: video_output_image (/mpv/build/../player/video.c:608)
   by 0x4A8194: write_video (/mpv/build/../player/video.c:756)
   by 0x49E62E: run_playloop (/mpv/build/../player/playloop.c:917)
```

**Comment by wm4** [comment]
Also sent a patch to ffmpeg-devel for the memcpy thing.
