### ISSUE TITLE
Deadlock with fuzzed file and --ao=null:untimed

### ISSUE THREAD

**Issue by tholin** [mpv-player/mpv#1473]
Trying to run the following file as `mpv --no-config --untimed --vo null --ao=null:untimed untimed_deadlock.ape` will deadlock mpv.
https://www.dropbox.com/s/imwfe45xwqc1hdd/untimed_deadlock.ape

So far I've run my fuzzers with `--untimed --vo null --no-audio` to avoid the deadlock but it would be nice if I could fuzz the audio decoders also.

```
$ gdb --args ~/repository/mpv-build_vanilla_debug/mpv/build/mpv --no-config --untimed --vo null --ao=null:untimed untimed_deadlock.ape 
GNU gdb (Gentoo 7.7.1 p1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/cocobo/repository/mpv-build_vanilla_debug/mpv/build/mpv...done.
(gdb) r
Starting program: /home/cocobo/repository/mpv-build_vanilla_debug/mpv/build/mpv --no-config --untimed --vo null --ao=null:untimed untimed_deadlock.ape
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffed4e7700 (LWP 32318)]
[New Thread 0x7fffecce6700 (LWP 32319)]
[New Thread 0x7fffe7fff700 (LWP 32320)]
Playing: untimed_deadlock.ape
[New Thread 0x7fffe77fe700 (LWP 32321)]
[Thread 0x7fffe77fe700 (LWP 32321) exited]
[New Thread 0x7fffe77fe700 (LWP 32322)]
[ffmpeg/demuxer] ape: Skipping binary tag 'Genre'.
[ffmpeg/demuxer] ape: Could not find codec parameters for stream 1 (Unknown: none): unknown codec       
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' and 'probesize' options        
[Thread 0x7fffe77fe700 (LWP 32322) exited]
 (+) Audio --aid=1 (ape)
File tags:
 Artist: vbAccelerator                 
 Album: None                         
 Comment: C
 Title: Concret                      
[New Thread 0x7fffe77fe700 (LWP 32323)]
[ffmpeg/audio] ape: Error decoding frame
Error decoding audio.                                                                                   
Error initializing audio.                                                                               
: 00:00:00 / 00:00:00 (0%)
Program received signal SIGINT, Interrupt.
0x00007ffff62f6341 in sem_timedwait () from /lib64/libpthread.so.0
(gdb) thread apply all bt

Thread 7 (Thread 0x7fffe77fe700 (LWP 32323)):
#0  0x00007ffff62f40bc in pthread_cond_wait () from /lib64/libpthread.so.0
#1  0x000000000043feeb in demux_thread (pctx=0x7fffd8203150) at ../demux/demux.c:499
#2  0x00007ffff62f0023 in start_thread () from /lib64/libpthread.so.0
#3  0x00007ffff1fd270d in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7fffe7fff700 (LWP 32320)):
#0  0x00007ffff62f448e in pthread_cond_timedwait () from /lib64/libpthread.so.0
#1  0x000000000052a565 in mpthread_cond_timedwait (cond=0x2051440, mutex=0x2051418, 
    abstime=9223372036854775807) at ../osdep/threads.c:34
#2  0x000000000047b990 in wait_wakeup (ctx=0x2051370, end=9223372036854775807)
    at ../player/client.c:286
#3  0x000000000047ced1 in mpv_wait_event (ctx=0x2051370, timeout=1e+20) at ../player/client.c:764
#4  0x0000000000497379 in script_wait_event (L=0x7fffe0000940) at ../player/lua.c:476
#5  0x00007ffff3189ba8 in luaD_precall () from /usr/lib64/liblua.so.5
#6  0x00007ffff3194287 in luaV_execute () from /usr/lib64/liblua.so.5
#7  0x00007ffff3189fed in luaD_call () from /usr/lib64/liblua.so.5
#8  0x00007ffff3185f15 in lua_call () from /usr/lib64/liblua.so.5
#9  0x000000000049687a in load_scripts (L=0x7fffe0000940) at ../player/lua.c:266
#10 0x00007ffff3189ba8 in luaD_precall () from /usr/lib64/liblua.so.5
#11 0x00007ffff3189fa4 in luaD_call () from /usr/lib64/liblua.so.5
#12 0x00007ffff318931b in luaD_rawrunprotected () from /usr/lib64/liblua.so.5
#13 0x00007ffff318a17a in luaD_pcall () from /usr/lib64/liblua.so.5
#14 0x00007ffff3185f9d in lua_pcall () from /usr/lib64/liblua.so.5
#15 0x0000000000496e20 in run_lua (L=0x7fffe0000940) at ../player/lua.c:358
#16 0x00007ffff3189ba8 in luaD_precall () from /usr/lib64/liblua.so.5
#17 0x00007ffff3189fa4 in luaD_call () from /usr/lib64/liblua.so.5
#18 0x00007ffff318931b in luaD_rawrunprotected () from /usr/lib64/liblua.so.5
#19 0x00007ffff318a17a in luaD_pcall () from /usr/lib64/liblua.so.5
#20 0x00007ffff3186017 in lua_cpcall () from /usr/lib64/liblua.so.5
#21 0x0000000000496f6b in load_lua (client=0x2051370, fname=0x2057590 "@ytdl_hook.lua")
    at ../player/lua.c:384
#22 0x00000000004a0741 in script_thread (p=0x20511e0) at ../player/scripting.c:86
#23 0x00007ffff62f0023 in start_thread () from /lib64/libpthread.so.0
#24 0x00007ffff1fd270d in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fffecce6700 (LWP 32319)):
#0  0x00007ffff62f448e in pthread_cond_timedwait () from /lib64/libpthread.so.0
#1  0x000000000052a565 in mpthread_cond_timedwait (cond=0x204ad30, mutex=0x204ad08, 
    abstime=9223372036854775807) at ../osdep/threads.c:34
#2  0x000000000047b990 in wait_wakeup (ctx=0x204ac60, end=9223372036854775807)
    at ../player/client.c:286
#3  0x000000000047ced1 in mpv_wait_event (ctx=0x204ac60, timeout=1e+20) at ../player/client.c:764
#4  0x0000000000497379 in script_wait_event (L=0x7fffe8000940) at ../player/lua.c:476
#5  0x00007ffff3189ba8 in luaD_precall () from /usr/lib64/liblua.so.5
#6  0x00007ffff3194287 in luaV_execute () from /usr/lib64/liblua.so.5
#7  0x00007ffff3189fed in luaD_call () from /usr/lib64/liblua.so.5
#8  0x00007ffff3185f15 in lua_call () from /usr/lib64/liblua.so.5
#9  0x000000000049687a in load_scripts (L=0x7fffe8000940) at ../player/lua.c:266
#10 0x00007ffff3189ba8 in luaD_precall () from /usr/lib64/liblua.so.5
#11 0x00007ffff3189fa4 in luaD_call () from /usr/lib64/liblua.so.5
#12 0x00007ffff318931b in luaD_rawrunprotected () from /usr/lib64/liblua.so.5
#13 0x00007ffff318a17a in luaD_pcall () from /usr/lib64/liblua.so.5
#14 0x00007ffff3185f9d in lua_pcall () from /usr/lib64/liblua.so.5
#15 0x0000000000496e20 in run_lua (L=0x7fffe8000940) at ../player/lua.c:358
#16 0x00007ffff3189ba8 in luaD_precall () from /usr/lib64/liblua.so.5
#17 0x00007ffff3189fa4 in luaD_call () from /usr/lib64/liblua.so.5
#18 0x00007ffff318931b in luaD_rawrunprotected () from /usr/lib64/liblua.so.5
#19 0x00007ffff318a17a in luaD_pcall () from /usr/lib64/liblua.so.5
#20 0x00007ffff3186017 in lua_cpcall () from /usr/lib64/liblua.so.5
#21 0x0000000000496f6b in load_lua (client=0x204ac60, fname=0x2050f20 "@osc.lua")
    at ../player/lua.c:384
#22 0x00000000004a0741 in script_thread (p=0x204aaf0) at ../player/scripting.c:86
#23 0x00007ffff62f0023 in start_thread () from /lib64/libpthread.so.0
#24 0x00007ffff1fd270d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fffed4e7700 (LWP 32318)):
#0  0x00007ffff1fc8ffd in poll () from /lib64/libc.so.6
#1  0x0000000000529b8c in terminal_thread (ptr=0x0) at ../osdep/terminal-unix.c:395
#2  0x00007ffff62f0023 in start_thread () from /lib64/libpthread.so.0
#3  0x00007ffff1fd270d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7f997c0 (LWP 32314)):
#0  0x00007ffff62f6341 in sem_timedwait () from /lib64/libpthread.so.0
#1  0x000000000045d487 in mp_input_wait (ictx=0x202cd40, seconds=100) at ../input/input.c:856
#2  0x000000000049c126 in mp_wait_events (mpctx=0x201e050, sleeptime=100) at ../player/playloop.c:59
#3  0x000000000049f174 in run_playloop (mpctx=0x201e050) at ../player/playloop.c:1003
#4  0x0000000000493761 in play_current_file (mpctx=0x201e050) at ../player/loadfile.c:1191
#5  0x0000000000493e7b in mp_play_files (mpctx=0x201e050) at ../player/loadfile.c:1348
#6  0x000000000049528a in mpv_main (argc=7, argv=0x7fffffffd9f8) at ../player/main.c:536
#7  0x0000000000411dcd in main (argc=7, argv=0x7fffffffd9f8) at ../player/main_fn.c:13
```

**Comment by wm4** [comment]
Not really a deadlock. What happens is that both audio and video are deselected, and then the player sits around doing nothing. It still accepts input.

In theory, the ``--stop-playback-on-init-failure`` option should make the player exit in this case, but that doesn't appear to work (or the option broke), so I should fix this.

Why is it allowed that no tracks are selected during playback? I don't have a clue...

**Comment by tholin** [comment]
Is there any way to force it to do both video and audio decoding in an untimed way?
I've tried this but it also stalls the same way `mpv --no-config --untimed --vo null --ao=pcm:file=/dev/null untimed_deadlock.ape`

**Comment by wm4** [comment]
The original command line you used should just work. This issue has nothing to do with untimed audio or anything.
