### ISSUE TITLE
failed to configure on MSYS2 with error: "No such file or directory: 'C:'"

### ISSUE THREAD

**Issue by amazingfate** [mpv-player/mpv#1486]
hereis the command:
```
python3.3.exe waf configure CC=gcc --enable-libmpv-static --disable-client-api-examples --prefix=/mingw64
```
here is error:
```
Checking for libavcodec avcodec_enum_to_chroma_pos API                    : Traceback (most recent call last):
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Scripting.py", line 98, in waf_entry_point
    run_commands()
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Scripting.py", line 159, in run_commands
    ctx=run_command(cmd_name)
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Scripting.py", line 150, in run_command
    ctx.execute()
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Configure.py", line 92, in execute
    super(ConfigurationContext,self).execute()
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/liujianfeng/mpv/wscript", line 876, in configure
    ctx.parse_dependencies(libav_dependencies)
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Configure.py", line 183, in fun
    return f(*k,**kw)
  File "/home/liujianfeng/mpv/waftools/dependencies.py", line 172, in parse_dependencies
    [__check_dependency__(ctx, dependency) for dependency in dependencies]
  File "/home/liujianfeng/mpv/waftools/dependencies.py", line 172, in <listcomp>
    [__check_dependency__(ctx, dependency) for dependency in dependencies]
  File "/home/liujianfeng/mpv/waftools/dependencies.py", line 170, in __check_dependency__
    dependency).check()
  File "/home/liujianfeng/mpv/waftools/dependencies.py", line 51, in check
    self.check_autodetect_func()
  File "/home/liujianfeng/mpv/waftools/dependencies.py", line 95, in check_autodetect_func
    if self.attributes['func'](self.ctx, self.identifier):
  File "/home/liujianfeng/mpv/waftools/checks/generic.py", line 60, in fn
    return ctx.check_cc(**_filter_cc_arguments(ctx, opts))
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Configure.py", line 183, in fun
    return f(*k,**kw)
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Tools/c_config.py", line 447, in check_cc
    return self.check(*k,**kw)
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Configure.py", line 183, in fun
    return f(*k,**kw)
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Tools/c_config.py", line 403, in check
    ret=self.run_build(*k,**kw)
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Configure.py", line 183, in fun
    return f(*k,**kw)
  File "/home/liujianfeng/mpv/.waf3-1.8.4-6442f4de997a9be97a56ebfe12e49ac5/waflib/Configure.py", line 341, in run_build
    shutil.rmtree(dir)
  File "/usr/lib/python3.3/shutil.py", line 464, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.3/shutil.py", line 402, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.3/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.3/shutil.py", line 420, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'C:'
```
seems to be the problem with python3, any ideas?

**Comment by wm4** [comment]
Or maybe a problem with waf. Hard to tell.

**Comment by rossy** [comment]
I'm not sure why this happens, but it happens on my machine when I have a native (mingw-w64) pkg-config in the $PATH.

To make sure the build uses the MSYS2 versions of Python and pkg-config, you could try running configure with this command:
```
PKG_CONFIG=/usr/bin/pkg-config /usr/bin/python3 CC=gcc --enable-libmpv-static --disable-client-api-examples --prefix=/mingw64
```

**Comment by amazingfate** [comment]
@rossy thank you very much it works!
