### ISSUE TITLE
waf-1.8.6 breaks build

### ISSUE THREAD

**Issue by 0-wiz-0** [mpv-player/mpv#1604]
mpv-0.7.3 built fine with waf-1.8.5. With waf-1.8.6 I see:

cd /scratch/multimedia/mpv/work/mpv-0.7.3 && /usr/bin/env CC=gcc CFLAGS=-O2\ -I/usr/pkg/include/lua-5.2\ -I/usr/include\ -I/usr/pkg/include\ -I/usr/pkg/include/libdrm\ -I/usr/pkg/include/freetype2\ -I/usr/pkg/include/ffmpeg2 CXX=c++ CXXFLAGS=-O2\ -I/usr/pkg/include/lua-5.2\ -I/usr/include\ -I/usr/pkg/include\ -I/usr/pkg/include/libdrm\ -I/usr/pkg/include/freetype2\ -I/usr/pkg/include/ffmpeg2 DESTDIR=/scratch/multimedia/mpv/work/.destdir LINKFLAGS=\ \ -L/usr/pkg/lib\ -Wl,-R/usr/pkg/lib\ -L/usr/lib\ -Wl,-R/usr/lib\ -L/usr/pkg/lib/pulseaudio\ -Wl,-R/usr/pkg/lib/pulseaudio\ -L/usr/pkg/lib/ffmpeg2\ -Wl,-R/usr/pkg/lib/ffmpeg2 PATH=/scratch/multimedia/mpv/work/.wrapper/bin:/scratch/multimedia/mpv/work/.buildlink/bin:/scratch/multimedia/mpv/work/.gcc/bin:/scratch/multimedia/mpv/work/.tools/bin:/usr/pkg/bin:/home/wiz/bin:/bin:/usr/bin:/usr/pkg/bin:/usr/X11R7/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/pkg/sbin:/usr/local/sbin:/usr/games:/usr/pkg/lib/surfraw PREFIX=/usr/pkg JOBS=8 ./waf --mandir=/usr/pkg/man
Waf: Entering directory `/scratch/multimedia/mpv/work/mpv-0.7.3/build'
Traceback (most recent call last):
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/.waf3-1.8.6-601a0f702a11ccd2399527bb9e0aadf2/waflib/Scripting.py", line 103, in waf_entry_point
    run_commands()
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/.waf3-1.8.6-601a0f702a11ccd2399527bb9e0aadf2/waflib/Scripting.py", line 164, in run_commands
    ctx=run_command(cmd_name)
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/.waf3-1.8.6-601a0f702a11ccd2399527bb9e0aadf2/waflib/Scripting.py", line 155, in run_command
    ctx.execute()
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/.waf3-1.8.6-601a0f702a11ccd2399527bb9e0aadf2/waflib/Scripting.py", line 366, in execute
    return execute_method(self)
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/.waf3-1.8.6-601a0f702a11ccd2399527bb9e0aadf2/waflib/Build.py", line 104, in execute
    self.execute_build()
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/.waf3-1.8.6-601a0f702a11ccd2399527bb9e0aadf2/waflib/Build.py", line 107, in execute_build
    self.recurse([self.run_dir])
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/.waf3-1.8.6-601a0f702a11ccd2399527bb9e0aadf2/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/wscript", line 922, in build
    ctx.load('wscript_build')
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/.waf3-1.8.6-601a0f702a11ccd2399527bb9e0aadf2/waflib/Context.py", line 89, in load
    fun(self)
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/wscript_build.py", line 41, in build
    ctx.load('waf_customizations')
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/.waf3-1.8.6-601a0f702a11ccd2399527bb9e0aadf2/waflib/Context.py", line 89, in load
    fun(self)
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/waftools/waf_customizations.py", line 35, in build
    class cprogram(cls):
  File "/scratch/multimedia/mpv/work/mpv-0.7.3/waftools/waf_customizations.py", line 36, in cprogram
    run_str = cls.hcode + '${LAST_LINKFLAGS}'
TypeError: can't concat bytes to str
*** Error code 2

I see the same error with mpv-0.8.0.

I've also filed https://code.google.com/p/waf/issues/detail?id=1535 about this in case this is a bug in waf.

**Comment by wm4** [comment]
I've applied the suggestion from the upstream bug report. Tell them my thanks for caring (I don't want to login with Google).

In general though, waf is _not_ downwards compatible. waf is supposed to copied into the project's sources, and new waf versions might require changes to the project files that break with older waf versions. mpv generally refuses to copy huge chunks of external code into its source repository, but these issues still apply to use. As a compromise we provide the ``bootstrap.py`` script, that downloads the correct waf version.
