### ISSUE TITLE
Failed to build PDF documentation for master branch (again)

### ISSUE THREAD

**Issue by SchweinDeBurg** [mpv-player/mpv#1630]
The same error returns - now with Python 2.7.9, ReportLab 3.1.44, rst2pdf 0.93.dev-r0:

Traceback (most recent call last):
  File "/opt/PSW/Python-2.7.9/bin/rst2pdf", line 9, in <module>
    load_entry_point('rst2pdf===0.93.dev-r0', 'console_scripts', 'rst2pdf')()
  File "/opt/PSW/Python-2.7.9/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 1495, in main
    compressed=options.compressed)
  File "/opt/PSW/Python-2.7.9/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 653, in createPdf
    pdfdoc.multiBuild(elements)
  File "/opt/PSW/Python-2.7.9/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 1007, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/opt/PSW/Python-2.7.9/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 920, in build
    self.handle_flowable(flowables)
  File "/opt/PSW/Python-2.7.9/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 801, in handle_flowable
    self.handle_frameEnd()
  File "/opt/PSW/Python-2.7.9/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 645, in handle_frameEnd
    self.handle_pageEnd()
  File "/opt/PSW/Python-2.7.9/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 593, in handle_pageEnd
    raise LayoutError(ident)
reportlab.platypus.doctemplate.LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.

**Comment by wm4** [comment]
Report a bug to rst2pdf or ReportLab. We can't fix this, and we can randomly rearrange the manpage every week to silence these errors either.

**Comment by mc4man** [comment]
@ SchweinDeBurg
if you are looking to create the pdf for yourself then usually failures can be easily resolved. Look at options.rst to make some adjustment.
Here just got first 2 failures, 1st. on ddbecd0 & then 4d0aa01 
for 4d0aa01 didn't bother with the moving nonsense, just removed 1 space near end of file & it built fine - 
ex.
.......
if there is enough interest).
This affects most third-party GUI frontends.

**Comment by lachs0r** [comment]
Well, had no problems for a while now. Maybe we’re just lucky, maybe ReportLab/rst2pdf got fixed…
Either way, worksforme™
