### ISSUE TITLE
Invalid free with -vo=xv -vf=expand in mpv 0.8.2

### ISSUE THREAD

**Issue by ghedo** [mpv-player/mpv#1698]
A user [reported](https://bugs.debian.org/779789) a crash when playing a [particular mp4 file](https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=3;filename=crash.mp4;att=1;bug=779789) while using the xv vo and the expand vf (both libav and ffmpeg builds), although I could not reproduce it.

The full command is:
```
mpv --no-config --vo=xv -vf=expand=::::1440/900 --msg-level=all=trace crash.mp4
```

Backtrace:
```
#0  0xf763d425 in __kernel_vsyscall ()
#1  0xf5b9d307 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xf5b9e9c3 in __GI_abort () at abort.c:89
#3  0xf5bdb6f8 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0xf5cd165c "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#4  0xf5be176a in malloc_printerr (action=<optimized out>, str=0xf5ccd172 "free(): invalid pointer", ptr=0xedf28020) at malloc.c:4996
#5  0xf5be23bd in _int_free (av=0x80808080, p=<optimized out>, have_lock=0) at malloc.c:3840
#6  0xf7720de2 in m_refcount_unref (ref=0xf87cc910) at ../video/mp_image.c:102
#7  0xf7758736 in ta_free (ptr=0xf87c4970) at ../ta/ta.c:259
#8  0xf77228f2 in unref_image (ptr=0xf87c4970) at ../video/mp_image_pool.c:109
#9  0xf7720de2 in m_refcount_unref (ref=0xf87cc7f0) at ../video/mp_image.c:102
#10 0xf7758736 in ta_free (ptr=0xf88f4178) at ../ta/ta.c:259
#11 0xf774e451 in uninit (vo=0xf87ba090) at ../video/out/vo_xv.c:694
#12 0xf7741e72 in vo_thread (ptr=0xf87ba090) at ../video/out/vo.c:754
#13 0xf63daefb in start_thread (arg=0xefcfcb40) at pthread_create.c:309
#14 0xf5c5862e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
```

valgrind output:
```
==2574== Invalid write of size 4
==2574==    at 0x482F85D: memset (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==2574==    by 0x1CA7A0: memset (string3.h:84)
==2574==    by 0x1CA7A0: memset_pic (memcpy_pic.h:57)
==2574==    by 0x1CA7A0: mp_image_clear (mp_image.c:440)
==2574==    by 0x1F86F6: allocate_xvimage (vo_xv.c:542)
==2574==    by 0x1F86F6: reconfig (vo_xv.c:471)
==2574==    by 0x1EA222: run_reconfig (vo.c:345)
==2574==    by 0x16AD5F: mp_dispatch_queue_process (dispatch.c:197)
==2574==    by 0x1EA535: vo_thread (vo.c:720)
==2574==    by 0x5A87EFA: start_thread (pthread_create.c:309)
==2574==    by 0x624162D: clone (clone.S:129)
==2574==  Address 0xefbb000 is not stack'd, malloc'd or (recently) free'd
```

[Full log](https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=19;filename=mpv.log;att=1;bug=779789) (the crash happens at the end).

**Comment by wm4** [comment]
Can't reproduce with git master or debian unstable's mpv.

**Comment by wm4** [comment]
I check all the code again, and all I found was a potential (but unlikely) issue which probably has nothing to do with this.

**Comment by ghedo** [comment]
Thanks. I asked the reporter to test the patch, I'll report back once I get an answer.

**Comment by wm4** [comment]
Can't reproduce, reporter apparently doesn't want to reply.
