### ISSUE TITLE
with lua enabled, mpv get SIGSEGV when open directories.

### ISSUE THREAD

**Issue by iyzsong** [mpv-player/mpv#1871]
Build with lua(5.2.3) enabled on master:
```
$ ./waf configure; ./waf build
$ ./build/mpv /tmp
Playing: /tmp
[file] This is a directory - adding to playlist.
Segmentation fault
```

then, I try gdb:
```
(gdb) bt
#0  0x00000000004e59ab in luaH_getstr ()
#1  0x00000000004e5a68 in luaH_get ()
#2  0x00000000004d5a63 in lua_rawget ()
#3  0x00007fffe5d11da2 in luaL_findtable () from /gnu/store/b95hahw6lvbs2z1ans8ilfjjfscyr8w9-lua-5.1.5/lib/liblua.so.5.1
#4  0x00007fffe5d11aaf in luaL_openlib () from /gnu/store/b95hahw6lvbs2z1ans8ilfjjfscyr8w9-lua-5.1.5/lib/liblua.so.5.1
#5  0x00007fffee7553ab in init_lua () from /gnu/store/1554bai2nqsc6p7qp3m6q48c7siq61ir-libquvi-0.4.1/lib/libquvi.so.7
#6  0x00007ffff5fe006d in ?? () from /gnu/store/ryag0hkns92p69hah38ijf6ng90gpvz9-ffmpeg-2.6.2/lib/libavformat.so.56
#7  0x00007ffff5fbece5 in av_probe_input_format3 () from /gnu/store/ryag0hkns92p69hah38ijf6ng90gpvz9-ffmpeg-2.6.2/lib/libavformat.so.56
#8  0x00007ffff5fbee92 in av_probe_input_format2 () from /gnu/store/ryag0hkns92p69hah38ijf6ng90gpvz9-ffmpeg-2.6.2/lib/libavformat.so.56
#9  0x000000000043df24 in lavf_check_file (check=<optimized out>, demuxer=0x7fffd02032b0) at ../demux/demux_lavf.c:341
#10 demux_open_lavf (demuxer=0x7fffd02032b0, check=<optimized out>) at ../demux/demux_lavf.c:666
#11 0x0000000000438b8d in open_given_type (check=DEMUX_CHECK_NORMAL, params=0x7fffdf7fde30, stream=0x7fffd0000a20, desc=0x50a040 <demuxer_desc_lavf>, 
    log=0x7fffd0000900, global=0x806fd0) at ../demux/demux.c:964
#12 demux_open (stream=0x7fffd0000a20, params=params@entry=0x7fffdf7fde30, global=global@entry=0x806fd0) at ../demux/demux.c:1029
#13 0x00000000004721b7 in open_demux_thread (pctx=0x7fffffffdeb0) at ../player/loadfile.c:951
#14 0x0000000000475ffe in thread_wrapper (pctx=0x7fffffffde20) at ../player/misc.c:275
#15 0x00007ffff164e464 in start_thread () from /gnu/store/0n7i54xn8fd81vh3qidlzrkgz3x59mkn-glibc-2.21/lib/libpthread.so.0
#16 0x00007ffff0d27edd in clone () from /gnu/store/0n7i54xn8fd81vh3qidlzrkgz3x59mkn-glibc-2.21/lib/libc.so.6

(gdb) info threads
  Id   Target Id         Frame 
  5    Thread 0x7fffe520b700 (LWP 19369) "mpv/terminal" 0x00007ffff0d1f33d in poll () from /gnu/store/0n7i54xn8fd81vh3qidlzrkgz3x59mkn-glibc-2.21/lib/libc.so.6
  4    Thread 0x7fffe4a0a700 (LWP 19370) "mpv/lua (osc)" 0x00007ffff1652ca8 in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /gnu/store/0n7i54xn8fd81vh3qidlzrkgz3x59mkn-glibc-2.21/lib/libpthread.so.0
  3    Thread 0x7fffdffff700 (LWP 19371) "mpv/lua (ytdl_h" 0x00007ffff1652ca8 in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /gnu/store/0n7i54xn8fd81vh3qidlzrkgz3x59mkn-glibc-2.21/lib/libpthread.so.0
* 2    Thread 0x7fffdf7fe700 (LWP 19373) "mpv/opener" 0x00000000004e59ab in luaH_getstr ()
  1    Thread 0x7ffff7fb37c0 (LWP 19365) "mpv" 0x00007ffff1654b12 in do_futex_wait () from /gnu/store/0n7i54xn8fd81vh3qidlzrkgz3x59mkn-glibc-2.21/lib/libpthread.so.0
```
When build with lua disabled, nothing bad happened.

**Comment by wm4** [comment]
Build ffmpeg without libquvi.

**Comment by iyzsong** [comment]
OK, thanks for the quick reply.
