### ISSUE TITLE
Cannot watch DVD (segmentation fault; probably libdvdnav related)

### ISSUE THREAD

**Issue by fturco** [mpv-player/mpv#1923]
I have a DVD that I can't watch with mpv because of a segmentation fault. The movie is Jurassic Park. Other DVDs can be played just fine. The DVD is in very good conditions and it is not scratched. My distribution is Parabola GNU/Linux-libre (an Arch Linux derivative). I rebuild both mpv and libdvdnav from source adding `'!strip'` to the `options` variable and adding `-O0 -fbuiltin -g` to C(XX)FLAGS. mpv version is 0.9.1-1. libdvdnav version is 5.0.2-1.

Here you are the backtrace I obtained with `gdb` (please tell me if you need other details):

```
Starting program: /usr/bin/mpv --no-config dvd://
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd7001700 (LWP 16220)]
[New Thread 0x7fffd7802700 (LWP 16219)]
[New Thread 0x7fffd8003700 (LWP 16218)]
[New Thread 0x7fffd8804700 (LWP 16217)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd7001700 (LWP 16220)]
0x00007ffff1a23af7 in dvdnav_describe_title_chapters (this=0x7fffcc000f20, 
    title=15, times=0x7fffd7000cc0, duration=0x7fffd7000cc8)
    at src/searching.c:650
650	    if (ptt[i].pgcn == 0 || ptt[i].pgcn > ifo->vts_pgcit->nr_of_pgci_srp) {

Thread 5 (Thread 0x7fffd8804700 (LWP 16217)):
#0  0x00007ffff00224ed in poll () from /usr/lib/libc.so.6
#1  0x00000000004d64fe in terminal_thread (ptr=<optimized out>)
    at ../osdep/terminal-unix.c:394
#2  0x00007ffff1804374 in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007ffff002b27d in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffd8003700 (LWP 16218)):
#0  0x00007ffff1809d58 in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
#1  0x00000000004d6f0b in mpthread_cond_timedwait (cond=cond@entry=0x7c4db0, 
    mutex=mutex@entry=0x7c4d88, abstime=abstime@entry=9223372036854775807)
    at ../osdep/threads.c:34
#2  0x0000000000461f92 in wait_wakeup (ctx=ctx@entry=0x7c4ce0, 
    end=end@entry=9223372036854775807) at ../player/client.c:288
#3  0x0000000000463e9b in mpv_wait_event (ctx=0x7c4ce0, 
    timeout=<optimized out>) at ../player/client.c:779
#4  0x0000000000476e33 in script_wait_event (L=0x7fffd0000940)
    at ../player/lua.c:481
#5  0x00007ffff291c07d in ?? () from /usr/lib/liblua.so.5.2
#6  0x00007ffff2927a3d in ?? () from /usr/lib/liblua.so.5.2
#7  0x00007ffff291c3f8 in ?? () from /usr/lib/liblua.so.5.2
#8  0x00007ffff291840b in lua_callk () from /usr/lib/liblua.so.5.2
#9  0x000000000047616a in load_scripts (L=0x7fffd0000940)
    at ../player/lua.c:266
#10 0x00007ffff291c07d in ?? () from /usr/lib/liblua.so.5.2
#11 0x00007ffff291c3c2 in ?? () from /usr/lib/liblua.so.5.2
#12 0x00007ffff291b9ff in ?? () from /usr/lib/liblua.so.5.2
#13 0x00007ffff291c651 in ?? () from /usr/lib/liblua.so.5.2
#14 0x00007ffff29184e6 in lua_pcallk () from /usr/lib/liblua.so.5.2
#15 0x0000000000477943 in run_lua (L=0x7fffd0000940) at ../player/lua.c:358
#16 0x00007ffff291c07d in ?? () from /usr/lib/liblua.so.5.2
#17 0x00007ffff291c3c2 in ?? () from /usr/lib/liblua.so.5.2
#18 0x00007ffff291b9ff in ?? () from /usr/lib/liblua.so.5.2
#19 0x00007ffff291c651 in ?? () from /usr/lib/liblua.so.5.2
#20 0x00007ffff29184e6 in lua_pcallk () from /usr/lib/liblua.so.5.2
#21 0x0000000000478062 in mp_cpcall (func=0x4774b0 <run_lua>, 
    ud=0x7fffd0000900, L=0x7fffd0000940) at ../player/lua.c:95
#22 load_lua (client=0x7c4ce0, fname=0x7cafb0 "@osc.lua")
    at ../player/lua.c:389
#23 0x000000000047cb8c in script_thread (p=0x7c4b70)
    at ../player/scripting.c:86
#24 0x00007ffff1804374 in start_thread () from /usr/lib/libpthread.so.0
#25 0x00007ffff002b27d in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffd7802700 (LWP 16219)):
#0  0x00007ffff1809d58 in pthread_cond_timedwait@@GLIBC_2.3.2 ()
   from /usr/lib/libpthread.so.0
#1  0x00000000004d6f0b in mpthread_cond_timedwait (cond=cond@entry=0x7cb500, 
    mutex=mutex@entry=0x7cb4d8, abstime=abstime@entry=9223372036854775807)
    at ../osdep/threads.c:34
#2  0x0000000000461f92 in wait_wakeup (ctx=ctx@entry=0x7cb430, 
    end=end@entry=9223372036854775807) at ../player/client.c:288
#3  0x0000000000463e9b in mpv_wait_event (ctx=0x7cb430, 
    timeout=<optimized out>) at ../player/client.c:779
#4  0x0000000000476e33 in script_wait_event (L=0x7fffc8000940)
    at ../player/lua.c:481
#5  0x00007ffff291c07d in ?? () from /usr/lib/liblua.so.5.2
#6  0x00007ffff2927a3d in ?? () from /usr/lib/liblua.so.5.2
#7  0x00007ffff291c3f8 in ?? () from /usr/lib/liblua.so.5.2
#8  0x00007ffff291840b in lua_callk () from /usr/lib/liblua.so.5.2
#9  0x000000000047616a in load_scripts (L=0x7fffc8000940)
    at ../player/lua.c:266
#10 0x00007ffff291c07d in ?? () from /usr/lib/liblua.so.5.2
#11 0x00007ffff291c3c2 in ?? () from /usr/lib/liblua.so.5.2
#12 0x00007ffff291b9ff in ?? () from /usr/lib/liblua.so.5.2
#13 0x00007ffff291c651 in ?? () from /usr/lib/liblua.so.5.2
#14 0x00007ffff29184e6 in lua_pcallk () from /usr/lib/liblua.so.5.2
#15 0x0000000000477943 in run_lua (L=0x7fffc8000940) at ../player/lua.c:358
#16 0x00007ffff291c07d in ?? () from /usr/lib/liblua.so.5.2
#17 0x00007ffff291c3c2 in ?? () from /usr/lib/liblua.so.5.2
#18 0x00007ffff291b9ff in ?? () from /usr/lib/liblua.so.5.2
#19 0x00007ffff291c651 in ?? () from /usr/lib/liblua.so.5.2
#20 0x00007ffff29184e6 in lua_pcallk () from /usr/lib/liblua.so.5.2
#21 0x0000000000478062 in mp_cpcall (func=0x4774b0 <run_lua>, 
    ud=0x7fffc8000900, L=0x7fffc8000940) at ../player/lua.c:95
#22 load_lua (client=0x7cb430, fname=0x7d1660 "@ytdl_hook.lua")
    at ../player/lua.c:389
#23 0x000000000047cb8c in script_thread (p=0x7cb2a0)
    at ../player/scripting.c:86
#24 0x00007ffff1804374 in start_thread () from /usr/lib/libpthread.so.0
#25 0x00007ffff002b27d in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffd7001700 (LWP 16220)):
#0  0x00007ffff1a23af7 in dvdnav_describe_title_chapters (this=0x7fffcc000f20, 
    title=15, times=0x7fffd7000cc0, duration=0x7fffd7000cc8)
    at src/searching.c:650
#1  0x000000000048d677 in open_s (stream=0x7fffd65fe050)
    at ../stream/stream_dvdnav.c:762
#2  0x00000000004846e5 in open_internal (ret=<synthetic pointer>, 
    global=0x7d19a0, c=0x798550, flags=0, url=<optimized out>, 
    sinfo=<optimized out>) at ../stream/stream.c:311
#3  stream_create (url=<optimized out>, flags=0, c=0x798550, global=0x7d19a0)
    at ../stream/stream.c:349
#4  0x00000000004705c7 in open_stream_thread (pctx=0x7fffffffe640)
    at ../player/loadfile.c:927
#5  0x000000000047469e in thread_wrapper (pctx=0x7fffffffe5a0)
    at ../player/misc.c:275
#6  0x00007ffff1804374 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff002b27d in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7f687c0 (LWP 16213)):
#0  0x00007ffff180bde3 in do_futex_wait () from /usr/lib/libpthread.so.0
#1  0x00007ffff180beaf in __new_sem_wait_slow () from /usr/lib/libpthread.so.0
#2  0x00007ffff180bf72 in sem_timedwait () from /usr/lib/libpthread.so.0
#3  0x000000000044d5b9 in mp_input_wait (ictx=0x7a6fb0, seconds=100)
    at ../input/input.c:844
#4  0x000000000047bdfa in mp_wait_events (sleeptime=<optimized out>, 
    mpctx=0x797950) at ../player/playloop.c:58
#5  mp_idle (mpctx=0x797950) at ../player/playloop.c:1049
#6  0x00000000004750a4 in mpctx_run_reentrant (mpctx=mpctx@entry=0x797950, 
    thread_fn=thread_fn@entry=0x4705b0 <open_stream_thread>, 
    thread_arg=thread_arg@entry=0x7fffffffe640) at ../player/misc.c:295
#7  0x00000000004726d5 in open_stream_reentrant (stream_flags=0, 
    filename=0x7cb200 "dvd://", mpctx=0x797950) at ../player/loadfile.c:940
#8  play_current_file (mpctx=0x797950) at ../player/loadfile.c:1089
#9  mp_play_files (mpctx=mpctx@entry=0x797950) at ../player/loadfile.c:1410
#10 0x00000000004745e4 in mpv_main (argc=<optimized out>, argv=0x7fffffffe7a8)
    at ../player/main.c:533
#11 0x00007fffeff63800 in __libc_start_main () from /usr/lib/libc.so.6
#12 0x0000000000414eb9 in _start ()
```

**Comment by wm4** [comment]
Relevant part of the backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd7001700 (LWP 16220)]
0x00007ffff1a23af7 in dvdnav_describe_title_chapters (this=0x7fffcc000f20, 
    title=15, times=0x7fffd7000cc0, duration=0x7fffd7000cc8)
    at src/searching.c:650
650     if (ptt[i].pgcn == 0 || ptt[i].pgcn > ifo->vts_pgcit->nr_of_pgci_srp) {

Thread 2 (Thread 0x7fffd7001700 (LWP 16220)):
#0  0x00007ffff1a23af7 in dvdnav_describe_title_chapters (this=0x7fffcc000f20, 
    title=15, times=0x7fffd7000cc0, duration=0x7fffd7000cc8)
    at src/searching.c:650
#1  0x000000000048d677 in open_s (stream=0x7fffd65fe050)
    at ../stream/stream_dvdnav.c:762
#2  0x00000000004846e5 in open_internal (ret=<synthetic pointer>, 
    global=0x7d19a0, c=0x798550, flags=0, url=<optimized out>, 
    sinfo=<optimized out>) at ../stream/stream.c:311
#3  stream_create (url=<optimized out>, flags=0, c=0x798550, global=0x7d19a0)
    at ../stream/stream.c:349
#4  0x00000000004705c7 in open_stream_thread (pctx=0x7fffffffe640)
    at ../player/loadfile.c:927
#5  0x000000000047469e in thread_wrapper (pctx=0x7fffffffe5a0)
    at ../player/misc.c:275
#6  0x00007ffff1804374 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff002b27d in clone () from /usr/lib/libc.so.6
```
Yes, this definitely looks like a libdvdnav issue. I suggest reporting it to that project instead.
