### ISSUE TITLE
Unnecessary resolution modification (eg. 854x480->854x481)

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#2067]
MPV unnecessarily change the resolution of the video (eg. 854x480->854x481)
```
mpv --no-config big_buck\ bunny_480p_h264.mkv
Playing: big_buck bunny_480p_h264.mkv
 (+) Video --vid=1 (h264)
VO: [opengl] 854x480 => 854x481 yuv420p
V: 00:00:02 / 00:05:00 (0%)
```

That can casue some issue with vapoursynth :
```
import vapoursynth as vs
core = vs.get_core()
clip = video_in
clip = core.deblock.Deblock(clip)
clip.set_output()
```

```
mpv --no-config --vf-add=vapoursynth=/media/Data/MyData/Linux/Softs/mpv/v.py big_buck\ bunny_480p_h264.mkv 
Playing: big_buck bunny_480p_h264.mkv
 (+) Video --vid=1 (h264)
Opening video filter: [vapoursynth file=/media/Data/MyData/Linux/Softs/mpv/v.py]
[vapoursynth] Script evaluation failed:
[vapoursynth] Python exception: Deblock: width and height must be mod 8
[vapoursynth] Traceback (most recent call last):
[vapoursynth]   File "vapoursynth.pyx", line 1469, in vapoursynth.vpy_evaluateScript (src/cython/vapoursynth.c:23703)
[vapoursynth]   File "/media/Data/MyData/Linux/Softs/mpv/v.py", line 4, in <module>
[vapoursynth]     clip = core.deblock.Deblock(clip)
[vapoursynth]   File "vapoursynth.pyx", line 1368, in vapoursynth.Function.__call__ (src/cython/vapoursynth.c:22272)
[vapoursynth] vapoursynth.Error: Deblock: width and height must be mod 8
[vapoursynth] 
Video filter chain:
  [vd] 854x480 yuv420p bt.709/limited CL=unknown
  [in] 854x480->854x481 yuv420p bt.709/limited CL=unknown
  [vapoursynth] 854x480->854x481 yuv420p bt.709/limited CL=unknown   <---
  [out] ???
Cannot initialize video filters.
Could not initialize video chain.
Video: no video
Exiting... (Errors when loading file)
```

**Comment by wm4** [comment]
These two issues have nothing to do with each other.

The 854x481 is from the aspect ratio. This is probably like this in the file, but hard to tell.

Vapoursynth fails because 854 is not divisible by 8.

**Comment by Paviluf** [comment]
> Vapoursynth fails because 854 is not divisible by 8.
Oh yes you are right, I was focused on 480 -> 481... Sorry

**Comment by Paviluf** [comment]
If that can help this is the output of mediainfo
```
General
Unique ID                                : 249386006990549252321563057279514564150 (0xBB9DFF7395942C1EAAC07BEDCC8DD636)
Complete name                            : /home/jeremy/big_buck bunny_480p_h264.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 88.2 MiB
Duration                                 : 5mn 0s
Overall bit rate                         : 2 465 Kbps
Encoded date                             : UTC 2011-08-09 23:47:50
Writing application                      : mkvmerge v4.9.1 ('Ich will') built on Jul 11 2011 23:53:15
Writing library                          : libebml v1.2.1 + libmatroska v1.1.1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.0
Format settings, CABAC                   : No
Format settings, ReFrames                : 2 frames
Format settings, GOP                     : M=2, N=24
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 5mn 0s
Bit rate                                 : 2 416 Kbps
Width                                    : 853 pixels
Original width                           : 854 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Original display aspect ratio            : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.246
Stream size                              : 86.4 MiB (98%)
Default                                  : Yes
Forced                                   : No
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Color range                              : Limited
```

**Comment by wm4** [comment]
Hm, forgot to close this.

**Comment by Paviluf** [comment]
Don't you think there is an error in 854x480->854x481 ?

**Comment by wm4** [comment]
The file headers probably indicate that this is correct, hard to tell.

**Comment by qyot27** [comment]
The AR flagging in this case makes the display resolution result in fractional pixels, which forces rounding to the nearest whole pixel.  480.375 (i.e. 854 / (16/9)) is being rounded up to 481 rather than down to 480, that's all.  It would also happen horizontally if the actual 853.3(repeating) value was used.

You could just get around it by using either ``--video-aspect 848:480 --vf scale=848:480`` or cropping it to 848x480 beforehand.  Probably.
