### ISSUE TITLE
Mesa: User error: GL_INVALID_OPERATION in VDPAUFiniNV

### ISSUE THREAD

**Issue by orbea** [mpv-player/mpv#2798]
os: Slackware-current

```
$ mpv --version
mpv git-563b478 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Feb  6 12:19:47 PST 2016
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.6
```

mesa: ea7f64f_2016.02.03
xf86-video-nouveau: b824d36_2016.01.13
libdrm: 682eaa0_2016.01.29

After compiling the latest mesa git today with debugging symbols I started getting this error output and xorg crashes when re-sizing the video window from fullscreen to windowed or vica versa. 

```
Mesa: User error: GL_INVALID_OPERATION in VDPAUFiniNV
```

So I set a breakpoint on output_if_debug in gdb.

```
(gdb) run --playlist playlist
Starting program: /usr/bin/mpv --playlist playlist
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4679700 (LWP 10216)]
[playlist] Reading plaintext playlist.
[Thread 0x7fffe4679700 (LWP 10216) exited]
[New Thread 0x7fffe4679700 (LWP 10217)]
[New Thread 0x7fffe8fc0700 (LWP 10218)]
[New Thread 0x7fffe87bf700 (LWP 10219)]
Playing: ./[ACX]Trinity_Blood_08_Silent_Noise_[SS_Alternative]_[3E0DABB8].mkv
[New Thread 0x7fffe7fbe700 (LWP 10220)]
[New Thread 0x7fffe77bd700 (LWP 10221)]
[Thread 0x7fffe7fbe700 (LWP 10220) exited]
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (vorbis)
     Audio --aid=2 --alang=jpn (vorbis)
 (+) Subs  --sid=1 --slang=eng (*) (ass)
File tags:
 Title: Trinity Blood 08 Silent Noise [AnimeCorpX]
[New Thread 0x7fffe7fbe700 (LWP 10222)]
[New Thread 0x7fffe6fbc700 (LWP 10223)]
[New Thread 0x7fffe67bb700 (LWP 10224)]
[New Thread 0x7fffe2a2d700 (LWP 10261)]
[New Thread 0x7fffe2114700 (LWP 10262)]
AO: [openal] 48000Hz stereo 2ch floatp
Using hardware decoding (vdpau).
VO: [opengl-hq] 720x480 => 768x480 vdpau
[Switching to Thread 0x7fffe6fbc700 (LWP 10223)]

Breakpoint 1, output_if_debug (prefixString=0x7fffe57cae6f "Mesa: User error", 
    outputString=0x7fffe6fbaac0 "GL_INVALID_OPERATION in VDPAUFiniNV", 
    newline=1 '\001') at main/errors.c:1317
1317       if (debug == -1) {
(gdb) bt full
#0  output_if_debug (prefixString=0x7fffe57cae6f "Mesa: User error", 
    outputString=0x7fffe6fbaac0 "GL_INVALID_OPERATION in VDPAUFiniNV", 
    newline=1 '\001') at main/errors.c:1317
        debug = -1
#1  0x00007fffe52d57e8 in _mesa_error (ctx=0x7fffd85131b0, error=1282, 
    fmtString=<optimized out>) at main/errors.c:1583
        s = "VDPAUFiniNV\000\377\177\000\000\001\000\000\000\000\000\000\000\263fh\345\377\177\000\000\000\000\000\000\000\000\000\000\070\027`\330\377\177\000\000\210\253\271\345\377\177\000\000\000@\260\351\377\177\000\000\220\211c\330\377\177\000\000\000\210c\330\377\177\000\000`\233\373\346\377\177\000\000\210L_\330\377\177\000\000\300\034b\330\377\177\000\000H\035b\330\377\177\000\000\320\035b\330\377\177\000\000\000\000\000\000\000\000\000\000\300\034b\330\377\177\000\000H\035b\330\377\177\000\000\320\035b\330\377\177\000\000\000\000\000\000\000\000\000\000\210\253\271\345\377\177\000\000\000\211c\330\377\177\000\000\300\226c\330\377\177\000\000\240rc\330\377\177\000\000Л\373\346\377\177\000\000x"...
        s2 = "GL_INVALID_OPERATION in VDPAUFiniNV", '\000' <repeats 277 times>...
        len = 35
        args = {{gp_offset = 24, fp_offset = 48, 
            overflow_arg_area = 0x7fffe6fbbbb0, reg_save_area = 0x7fffe6fbbac0}}
        do_log = 0 '\000'
        error_msg_id = 1
        __PRETTY_FUNCTION__ = "_mesa_error"
#2  0x00000000004abbbf in ?? ()
No symbol table info available.
#3  0x00000000004abc5f in ?? ()
No symbol table info available.
#4  0x00000000004b74d5 in ?? ()
No symbol table info available.
#5  0x00000000004bd96e in ?? ()
No symbol table info available.
#6  0x00000000004b920b in ?? ()
No symbol table info available.
#7  0x0000000000449c3f in ?? ()
No symbol table info available.
#8  0x00000000004ba07d in ?? ()
No symbol table info available.
#9  0x00007ffff79af704 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#10 0x00007ffff179af8d in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by orbea** [comment]
Additionally watching videos spams dmesg and /var/log/syslog which can quickly fill up a small partition...

dmesg:
```
[  182.181376] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.181437] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.223498] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.223556] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.264543] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.264608] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.309569] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.309606] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.350131] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.350152] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.392631] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.392703] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.433546] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.433628] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.464546] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.464585] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.515110] nouveau 0000:01:00.0: DRM: skipped size 0
[  182.515965] nouveau 0000:01:00.0: DRM: skipped size 0
```
/var/log/syslog:
```
Feb  6 18:43:06 Akita kernel: [  174.597778] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:06 Akita kernel: [  174.670133] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:06 Akita kernel: [  174.877029] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:06 Akita kernel: [  175.058063] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:06 Akita kernel: [  175.058073] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.251820] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.251829] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.261170] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.261178] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.306271] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.306548] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.433684] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.434935] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.434942] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.435322] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.435326] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.435630] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.435635] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.442627] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.480309] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.480357] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.480362] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.510688] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.510741] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.510747] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.550918] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.550984] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.550994] nouveau 0000:01:00.0: DRM: skipped size 0
Feb  6 18:43:07 Akita kernel: [  175.590390] nouveau 0000:01:00.0: DRM: skipped size 0
```

**Comment by imirkin** [comment]
FYI the messages mean that nouveau is (mistakenly) allocating a 0-sized buffer. This is normally not allowed. However the only way that would happen would be if someone asked the driver to create a 0x0 surface, which probably shouldn't happen either.

**Comment by orbea** [comment]
The error message is only with a debug version of mesa, the dmesg spam is regardless.

**Comment by orbea** [comment]
The Mesa: User Error does not seem to be a mpv specific issue, MPlayer is also affected.
However the dmesg spam does appear to be a mpv specific issue... Could these be unrelated issues?
```
(gdb) run -vo gl Dark.Matter.S01E01.720p.HDTV.x264-KILLERS.mkv 
Starting program: /usr/bin/mplayer -vo gl Dark.Matter.S01E01.720p.HDTV.x264-KILLERS.mkv
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
MPlayer 1.2.1-5.3.0 (C) 2000-2016 MPlayer Team

Playing Dark.Matter.S01E01.720p.HDTV.x264-KILLERS.mkv.
libavformat version 56.40.101 (internal)
libavformat file format detected.
[lavf] stream 0: video (h264), -vid 0
[lavf] stream 1: audio (ac3), -aid 0
VIDEO:  [H264]  1280x720  0bpp  23.976 fps    0.0 kbps ( 0.0 kbyte/s)
Clip info:
 encoder: libebml v1.3.0 + libmatroska v1.4.1
 creation_time: 2015-06-13 03:05:22
Load subtitles in ./
[gl] using extended formats. Use -vo gl:nomanyfmts if playback fails.
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 56.60.100 (internal)
Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)
==========================================================================
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
[ac3 @ 0x5555568beb80]Channel layout '5.1(side)' with 6 channels does not match specified number of channels 2: ignoring specified channel layout
AUDIO: 48000 Hz, 2 ch, floatle, 384.0 kbit/12.50% (ratio: 48000->384000)
Selected audio codec: [ffac3] afm: ffmpeg (FFmpeg AC-3)
==========================================================================
AO: [alsa] 48000Hz 2ch floatle (4 bytes per sample)
Starting playback...
Movie-Aspect is 1.60:1 - prescaling to correct movie aspect.
VO: [gl] 1280x720 => 1280x800 Planar YV12 

Breakpoint 1, output_if_debug (prefixString=0x7fffea04be6f "Mesa: User error", 
    outputString=0x7fffffffbb70 "GL_INVALID_ENUM in glTexParameter(pname=GL_TEXTURE_STORAGE_HINT_APPLE)", newline=1 '\001') at main/errors.c:1317
warning: Source file is more recent than executable.
1317       if (debug == -1) {
(gdb) bt full
#0  output_if_debug (prefixString=0x7fffea04be6f "Mesa: User error", 
    outputString=0x7fffffffbb70 "GL_INVALID_ENUM in glTexParameter(pname=GL_TEXTURE_STORAGE_HINT_APPLE)", newline=1 '\001') at main/errors.c:1317
        debug = -1
#1  0x00007fffe9b567e8 in _mesa_error (ctx=ctx@entry=0x555557bd9a50, 
    error=error@entry=1280, fmtString=<optimized out>) at main/errors.c:1583
        s = "glTexParameter(pname=GL_TEXTURE_STORAGE_HINT_APPLE)\000\377\177\000\000\000\223\300WUU\000\000\002\000\000\000UU\000\000\030\000\000\000\000\000\000\000\060\254\377\377\377\177\000\000\030\000\000\000\000\000\000\000@\254\377\377\377\177\000\000\220\351\300WUU\000\000\321S\000\000\000\200\377\377/\254\377\377\377\177\000\000\000\000\000\000\000\000\000\000\002\000\000\000\060", '\000' <repeats 19 times>, "[\000\000\000n", '\000' <repeats 19 times>, "w\000\000\000|", '\000' <repeats 11 times>...
        s2 = "GL_INVALID_ENUM in glTexParameter(pname=GL_TEXTURE_STORAGE_HINT_APPLE)", '\000' <repeats 62 times>, "\377\177\000\000@˗\360\377\177\000\000\000\000\000\000\000\000\000\000^@c\360\377\177\000\000\300\301\377\377\377\177\000\000\260\301\377\377\377\177\000\000P\211\a\352\377\177\000\000(\303\377\377\377\177\000\000\000\000\000\000\000\000\000\000\340"...
        len = 70
        args = {{gp_offset = 40, fp_offset = 48, 
            overflow_arg_area = 0x7fffffffcc60, reg_save_area = 0x7fffffffcb70}}
        do_log = 0 '\000'
        error_msg_id = 1
        __PRETTY_FUNCTION__ = "_mesa_error"
#2  0x00007fffe9c203cb in set_tex_parameteri (ctx=ctx@entry=0x555557bd9a50, 
    texObj=texObj@entry=0x555557c01da0, pname=pname@entry=34236, 
    params=params@entry=0x7fffffffcca0, dsa=<optimized out>)
    at main/texparam.c:629
        suffix = 0x7fffea0d1f94 ""
#3  0x00007fffe9c21686 in _mesa_texture_parameteri (ctx=0x555557bd9a50, 
    texObj=0x555557c01da0, pname=34236, param=34238, dsa=<optimized out>)
    at main/texparam.c:919
        iparam = {34238, 0, 0, 0}
        need_update = <optimized out>
#4  0x00005555556cca4b in ?? ()
No symbol table info available.
#5  0x00005555556d28de in ?? ()
No symbol table info available.
#6  0x00005555556d2e58 in ?? ()
No symbol table info available.
#7  0x00005555556bd9fe in ?? ()
No symbol table info available.
#8  0x0000555555782157 in ?? ()
No symbol table info available.
#9  0x000055555574fa8f in ?? ()
No symbol table info available.
#10 0x000055555574bd5c in ?? ()
No symbol table info available.
#11 0x0000555555811c97 in ?? ()
No symbol table info available.
#12 0x00005555558121d0 in ?? ()
No symbol table info available.
#13 0x0000555555747082 in ?? ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#14 0x00005555556b30fd in ?? ()
No symbol table info available.
#15 0x00005555556a5597 in ?? ()
No symbol table info available.
#16 0x00007ffff05d66d0 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#17 0x00005555556a7a39 in ?? ()
No symbol table info available.
```

**Comment by orbea** [comment]
Thanks, that seemed to have stopped the mesa user error, however I am still getting spammed in dmesg while watching videos especially with hwdec which will eventually freeze my computer if ignored...  Could they be separate issues? 

This has gotten me to use mplayer again for hwdec and that is making me greater realize how mpv is far better with everything else...

**Comment by wm4** [comment]
Like imirkin said in #2799, nouveau can't deal with vdpau accesses from different threads.

Thus this can't be fixed in mpv.

**Comment by imirkin** [comment]
Well, it certainly *could* be fixed in mpv (e.g. you could have an option to not do that), but you can also decide not to bend over backwards for imperfect drivers.

The issue, btw, is not access from different threads, it's simultaneous command submission from multiple threads. If you interlocked them, then this wouldn't be an issue.

**Comment by orbea** [comment]
@lachs0r This has not been fixed.

**Comment by lachs0r** [comment]
Then open a bug at nouveau’s tracker or install proper drivers for your hardware.

**Comment by orbea** [comment]
There already exists at least one issue concerning crashes with nouveau when using concurrent opengl and / or vdpau calls. Making another one is not going to help the nouveau devs fix this any faster, imirkin has a locking branch that may eventually solve this, but as I understand its not ready yet.

Keeping this open will help nouveau users find this issue and would be a nice gesture. I would think under ideal circumstances mpv should take steps to not crash someone's system regardless of what video driver they use.

**Comment by wm4** [comment]
> I would think under ideal circumstances mpv should take steps to not crash someone's system regardless of what video driver they use.

HAHAHAHAHAHA. Go ask your driver authors not to enable buggy API implementations by default that crash applications that (apparently) use the API correctly.

**Comment by orbea** [comment]
That is a rather unfortunate attitude. :(

**Comment by wm4** [comment]
It's the only reasonable one.
