### ISSUE TITLE
[ytdl_hook] youtube-dl failed

### ISSUE THREAD

**Issue by CrisBRM** [mpv-player/mpv#2897]
```
mpv https://www.youtube.com/watch?v=GiVs05yq9-o
Playing: https://www.youtube.com/watch?v=GiVs05yq9-o
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "/usr/bin/youtube-dl", line 3, in <module>
[ytdl_hook]     import youtube_dl
[ytdl_hook]   File "/usr/lib64/python2.7/site-packages/youtube_dl/__init__.py", line 15, in <module>
[ytdl_hook]     from .options import (
[ytdl_hook]   File "/usr/lib64/python2.7/site-packages/youtube_dl/options.py", line 7, in <module>
[ytdl_hook]     from .downloader.external import list_external_downloaders
[ytdl_hook]   File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/__init__.py", line 3, in <module>
[ytdl_hook]     from .common import FileDownloader
[ytdl_hook]   File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/common.py", line 8, in <module>
[ytdl_hook]     from ..utils import (
[ytdl_hook]   File "/usr/lib64/python2.7/site-packages/youtube_dl/utils.py", line 27, in <module>
[ytdl_hook]     import ssl
[ytdl_hook]   File "/usr/lib64/python2.7/ssl.py", line 97, in <module>
[ytdl_hook]     import _ssl             # if we can't import it, let the error propagate
[ytdl_hook] ImportError: /usr/lib64/python2.7/lib-dynload/_ssl.so: undefined symbol: SSLv2_method
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
Failed to recognize file format.


Exiting... (Errors when loading file)
```

Default settings (for debugging purposes) and youtube-dl-2016.03.01.

**Comment by kevmitch** [comment]
Your python ssl module is messed up. Your distro probably needs to be recompile it against it's current openssl library.

**Comment by CrisBRM** [comment]
Thanks.
