### ISSUE TITLE
Doesn't mpv use youtube-dl config file?

### ISSUE THREAD

**Issue by seb321** [mpv-player/mpv#3249]
Hi,
(sorry for my English, it isn't my native language)
for test I made youtube-dl config file:

>--external-downloader aria2c
>--external-downloader-args="-j 16 **-s 0** -x 16"

youtube-dl gives error:
>  youtube-dl https://www.youtube.com/watch\?v\=y6120QOlsfU
[youtube] y6120QOlsfU: Downloading webpage
[youtube] y6120QOlsfU: Downloading video info webpage
[youtube] y6120QOlsfU: Extracting video information
[youtube] y6120QOlsfU: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Darude - Sandstorm-y6120QOlsfU.f134.mp4
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2016.5.10', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 421, in main
    _real_main(argv)
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 411, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1735, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 687, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 732, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1381, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1637, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1585, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.5/site-packages/youtube_dl/downloader/external.py", line 28, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
  File "/usr/lib/python3.5/site-packages/youtube_dl/downloader/external.py", line 88, in _call_downloader
    self.to_stderr(stderr)
  File "/usr/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 149, in to_stderr
    self.ydl.to_screen(message)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 433, in to_screen
    return self.to_stdout(message, skip_eol, check_quiet=True)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 445, in to_stdout
    output = message + terminator
TypeError: can't concat bytes to str

with `-s 1` everything is ok:
>youtube-dl https://www.youtube.com/watch\?v\=y6120QOlsfU
[youtube] y6120QOlsfU: Downloading webpage
[youtube] y6120QOlsfU: Downloading video info webpage
[youtube] y6120QOlsfU: Extracting video information
[youtube] y6120QOlsfU: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Darude - Sandstorm-y6120QOlsfU.f134.mp4
[#5174f4 12MiB/14MiB(88%) CN:1 DL:1.2MiB ETA:1s]^C                                                  

>ERROR: Interrupted by user

however mpv with `-s 0` plays video without any error:
>mpv --msg-level=ytdl_hook=debug https://www.youtube.com/watch\?v\=y6120QOlsfU
[ytdl_hook] Loading script @ytdl_hook.lua...
[ytdl_hook] loading mp.defaults
[ytdl_hook] loading @ytdl_hook.lua
Playing: https://www.youtube.com/watch?v=y6120QOlsfU
[ytdl_hook] Running: youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --no-playlist --all-subs -- https://www.youtube.com/watch?v=y6120QOlsfU 
[ytdl_hook] youtube-dl succeeded! 
[ytdl_hook] streamurl: https://r3---sn-u2oxu-f5fk.googlevideo.com/videoplayback?id=cbad76d103a5b1f5&itag=134&source=youtube&requiressl=yes&mn=sn-u2oxu-f5fk&initcwndbps=920000&pcm2cms=yes&ms=au&mv=m&pl=24&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=15015601&lmt=1458208637892716&dur=232.280&fexp=9405186,9408207,9416126,9416891,9417703,9419452,9422596,9423194,9426687,9428398,9431012,9432684,9433096,9433380,9433458,9433946,9435385,9435526,9435876,9436018,9436120,9437066,9437230,9437286,9437553,9438327,9438804&signature=7884618DD021129BB38D1A0CAFF819F1344B58BB.189453C472AE9EA44382AB36E73A249623C784EF&mt=1465913350&upn=pn2IB1i_V9k&key=dg_yt0&sver=3&ip=83.28.205.153&ipbits=0&expire=1465935447&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,initcwndbps,pcm2cms,ms,mv,pl,mm,ratebypass,mime,gir,clen,lmt,dur 
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (opus) (external)
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 640x356 yuv420p
AV: 00:00:02 / 00:03:52 (0%) A-V:  0.000 Cache: 10s+1MB

So It seems that mpv doesn't use youtube-dl config file. Is there any way to force using it?. Or am I wrong?

**Comment by wiiaboo** [comment]
mpv just gets uses youtube-dl to get URLs and other info, it doesn't use youtube-dl for downloads. It should use youtube-dl.conf for some other options, though.

**Comment by seb321** [comment]
Don't know that,
thanks.
