### ISSUE TITLE
PDF generation failed... again

### ISSUE THREAD

**Issue by SchweinDeBurg** [mpv-player/mpv#3563]
Commit 89674854ceaae9c0a9d8f24b9a24fb2f24df6bb1

```
Traceback (most recent call last):
  File "/usr/libexec/python2.7/rst2pdf", line 9, in <module>
    load_entry_point('rst2pdf===0.93.dev-r0', 'console_scripts', 'rst2pdf')()
  File "/usr/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 1495, in main
    compressed=options.compressed)
  File "/usr/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 653, in createPdf
    pdfdoc.multiBuild(elements)
  File "/usr/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 1043, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/usr/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 956, in build
    self.handle_flowable(flowables)
  File "/usr/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 801, in handle_flowable
    self.handle_frameEnd()
  File "/usr/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 670, in handle_frameEnd
    self.handle_pageEnd()
  File "/usr/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 616, in handle_pageEnd
    raise LayoutError(ident)
reportlab.platypus.doctemplate.LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.
```

**Comment by wm4** [comment]
Can you report this upstream?

**Comment by shinchiro** [comment]
This caused by commit 6b5e5b6 specifically at changing `NOTE:` to `.. note::`

**Comment by wm4** [comment]
Doesn't matter. It's valid RST.

**Comment by kevmitch** [comment]
[rst2pdf #597](https://github.com/rst2pdf/rst2pdf/issues/597)

**Comment by lachs0r** [comment]
No idea whether it was c3ae2ff107ab15902e6d0555b5e0d0a17c9af154 but this is “fixed”.
