### ISSUE TITLE
Configuration error with missing libavfilter

### ISSUE THREAD

**Issue by ita1024** [mpv-player/mpv#3692]
### mpv version and platform

git master

### Reproduction steps

waf configure

### Expected behavior

Error message.

### Actual behavior

```
waf configure
...
Checking for libavfilter                                             : no ('libavfilter >= 5.0.0' not found) 
Traceback (most recent call last):
  File "/home/user/waf/waflib/Scripting.py", line 165, in waf_entry_point
    run_commands()
  File "/home/user/waf/waflib/Scripting.py", line 266, in run_commands
    ctx = run_command(cmd_name)
  File "/home/user/waf/waflib/Scripting.py", line 250, in run_command
    ctx.execute()
  File "/home/user/waf/waflib/Configure.py", line 159, in execute
    super(ConfigurationContext, self).execute()
  File "/home/user/waf/waflib/Context.py", line 205, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/user/waf/waflib/Context.py", line 287, in recurse
    user_function(self)
  File "/home/user/mpv/wscript", line 1058, in configure
    ctx.parse_dependencies(libav_dependencies)
  File "/home/user/waf/waflib/Configure.py", line 317, in fun
    return f(*k, **kw)
  File "/home/user/mpv/waftools/dependencies.py", line 172, in parse_dependencies
    [__check_dependency__(ctx, dependency) for dependency in dependencies]
  File "/home/user/mpv/waftools/dependencies.py", line 170, in __check_dependency__
    dependency).check()
  File "/home/user/mpv/waftools/dependencies.py", line 50, in check
    self.check_autodetect_func()
  File "/home/user/mpv/waftools/dependencies.py", line 99, in check_autodetect_func
    self.fatal_if_needed()
  File "/home/user/mpv/waftools/dependencies.py", line 122, in fatal_if_needed
    raise ConfigurationError(self.attributes['fmsg'])
KeyError: 'fmsg'
```

### Log file

```
Checking for libavfilter
['/usr/bin/pkg-config', 'libavfilter >= 5.0.0', '--libs', '--cflags', 'libavfilter']
err: Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found

from /home/user/mpv: The configuration failed
no ('libavfilter >= 5.0.0' not found)
```

**Comment by wm4** [comment]
Better now? (Didn't test.)

**Comment by ita1024** [comment]
Yes, it is fixed.

**Comment by ita1024** [comment]
Setting a default message might be a good idea to avoid similar errors in the future

```python
diff --git a/waftools/dependencies.py b/waftools/dependencies.py
index c1f3fdb..f263ac6 100644
--- a/waftools/dependencies.py
+++ b/waftools/dependencies.py
@@ -119,7 +119,7 @@ the autodetection check failed.".format(self.identifier)
         if self.enabled_option() == False:
             return
         if self.attributes.get('req', False):
-            raise ConfigurationError(self.attributes['fmsg'])
+            raise ConfigurationError(self.attributes.get('fmsg', 'required'))
 
     def skip(self, reason='disabled', color='YELLOW'):
         self.ctx.end_msg(self.__message__(reason), color)
```

**Comment by wm4** [comment]
Yeah. Can you PR it?

**Comment by ita1024** [comment]
Yes, we can.
