### ISSUE TITLE
Segmentation fault when open ".cue" file

### ISSUE THREAD

**Issue by ERYuyNIrbNKrsc** [mpv-player/mpv#5027]
### mpv version and platform

mpv 0.27.0-270-g0358cca39e (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 22 18:22:45 EEST 2017
ffmpeg library versions:
   libavutil       56.0.100
   libavcodec      58.0.100
   libavformat     58.0.100
   libswscale      5.0.100
   libavfilter     7.0.100
   libswresample   3.0.100
ffmpeg version: N-88041-gb89081e01b

Kubuntu 17.10 amd64

### Reproduction steps

open ".cue" file

### Expected behavior

play music

### Actual behavior

Segmentation fault

### Log file

http://sprunge.us/iTEI

```
(gdb) r --log-file=output.txt "KISIDA KYODAN & THE AKEBOSI ROCKETS - Strike the Blood.cue"
Starting program: /usr/local/bin/mpv --log-file=output.txt "KISIDA KYODAN & THE AKEBOSI ROCKETS - Strike the Blood.cue"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec57a700 (LWP 20850)]
[New Thread 0x7fffebd79700 (LWP 20851)]
[New Thread 0x7fffeb578700 (LWP 20852)]
[New Thread 0x7fffeab93700 (LWP 20853)]
[New Thread 0x7fffea332700 (LWP 20854)]
[New Thread 0x7fffe9aca700 (LWP 20855)]
Playing: KISIDA KYODAN & THE AKEBOSI ROCKETS - Strike the Blood.cue
[New Thread 0x7fffe9289700 (LWP 20856)]
[Thread 0x7fffe9289700 (LWP 20856) exited]
[New Thread 0x7fffe9289700 (LWP 20857)]
 (+) Audio --aid=1 --alang=und (*) (aac 2ch 44100Hz)

Thread 1 "mpv" received signal SIGSEGV, Segmentation fault.
audio_select_decoders (d_audio=0x5555573ca460) at ../audio/decode/dec_audio.c:88
88          const char *codec = d_audio->codec->codec;
(gdb) backtrace 
#0  audio_select_decoders (d_audio=0x5555573ca460) at ../audio/decode/dec_audio.c:88
#1  audio_init_best_codec (d_audio=d_audio@entry=0x5555573ca460) at ../audio/decode/dec_audio.c:121
#2  0x00005555556dea67 in audio_work (da=0x5555573ca460) at ../audio/decode/dec_audio.c:257
#3  0x00005555557293fe in decode_new_frame (ao_c=0x5555573c9420) at ../player/audio.c:952
#4  0x000055555572aeff in decode_new_frame (ao_c=<optimized out>) at ../player/audio.c:945
#5  fill_audio_out_buffers (mpctx=mpctx@entry=0x5555573487b0) at ../player/audio.c:1125
#6  0x000055555574bc98 in run_playloop (mpctx=mpctx@entry=0x5555573487b0) at ../player/playloop.c:1085
#7  0x0000555555741f1d in play_current_file (mpctx=0x5555573487b0) at ../player/loadfile.c:1358
#8  mp_play_files (mpctx=mpctx@entry=0x5555573487b0) at ../player/loadfile.c:1519
#9  0x0000555555742be1 in mpv_main (argc=<optimized out>, argv=<optimized out>) at ../player/main.c:494
#10 0x00007ffff21151c1 in __libc_start_main (main=0x5555556d6df0 <main>, argc=3, argv=0x7fffffffc8c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffc8b8)
    at ../csu/libc-start.c:308
#11 0x00005555556d6e2a in _start ()
(gdb)
```

### Sample files

https://0x0.st/srWV.zip

**Comment by h633537** [comment]
Commit that broke it was [719a435d3636c7b848b49f06e6a2ea55e7ee656a](https://github.com/mpv-player/mpv/commit/719a435d3636c7b848b49f06e6a2ea55e7ee656a)
I also get a segfault with files using ordered chapters
