### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by vaurelios** [mpv-player/mpv#5040]
### mpv version and platform
```
mpv --version         
Warning: option --sub-text-color was replaced with --sub-color and might be removed in the future.
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed Sep 13 10:50:48 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.4
```

### Reproduction steps
play a movie with following config:
```
hwdec=vdpau
vo=vdpau
sub-pos=0
sub-gauss=3.0
sub-blur=0
sub-bold=yes
sub-border-size=0
sub-back-color="#000000"
sub-border-color="#ff783a"
sub-text-color="#FF4F00"
stretch-image-subs-to-screen
sub-use-margins
no-keepaspect
```

### Expected behavior
Play entire video.
### Actual behavior
Crashes randomly, with same movie at same position, position varies with movies.
### Log file
coredump:
Stack trace of thread 31637:
```
#0  0x00007f03ee93dfd1 __libc_free (libc.so.6)
#1  0x00007f03f1f2fbfb n/a (libass.so.9)
#2  0x00007f03f1f30c5f ass_render_frame (libass.so.9)
#3  0x000055a8c4fe6d84 n/a (mpv)
#4  0x000055a8c4fe3a83 n/a (mpv)
#5  0x000055a8c5029337 n/a (mpv)
#6  0x000055a8c50212c3 n/a (mpv)
#7  0x00007f03f422c08a start_thread (libpthread.so.0)
#8  0x00007f03ee9b11bf __clone (libc.so.6)

```

**Comment by vaurelios** [comment]
This is a regression, but I can't remember which version works ok.

**Comment by CounterPillow** [comment]
Your stack trace is not terribly helpful, because it is stripped of most symbols.

**Comment by vaurelios** [comment]
Still happens with `version 0.29.1`

[Core dump](https://drive.google.com/open?id=1Fb0ZhOuKvdROQ02J9nOnctzlDu89lCKY) (now with ass and mpv debug symbols)

PS: sorry for the response delay.

**Comment by CounterPillow** [comment]
Coredump isn't terribly helpful if we don't have the exact mpv binary you have. Can't you post a full backtrace generated with gdb?

**Comment by vaurelios** [comment]
Here you go:
```
#0  0x00007f044cd36f41 in free () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f043cd0e700 (LWP 16029))]
(gdb) bt
#0  0x00007f044cd36f41 in free () from /usr/lib/libc.so.6
#1  0x00007f045119416f in ass_aligned_free (ptr=<optimized out>)
    at ass_utils.c:103
#2  0x00007f045119ceae in ass_frame_unref (img=0x7f042cce72f0)
    at ass_render.c:2942
#3  ass_frame_unref (img=<optimized out>) at ass_render.c:2932
#4  0x00007f045119e616 in ass_render_frame (priv=priv@entry=0x55bd7aa3d8b0, 
    track=track@entry=0x55bd7aa3fdf0, now=now@entry=1128085, 
    detect_change=detect_change@entry=0x7f043cd0c58c) at ass_render.c:2911
#5  0x000055bd783e1a76 in get_bitmaps (sd=0x55bd7aa3ab30, dim=..., format=1, 
    pts=1128.0852916684451, res=0x7f043cd0c6e0) at ../sub/sd_ass.c:471
#6  0x000055bd783dea69 in render_object (out_imgs=0x7f043cd0c6e0, 
    sub_formats=0x7f042c63e468, video_pts=1128.0852916684451, res=..., 
    obj=0x55bd7a4fb250, osd=0x55bd7a4e1dd0) at ../sub/osd.c:277
#7  osd_draw (osd=0x55bd7a4e1dd0, res=..., video_pts=1128.0852916684451, 
    draw_flags=0, formats=formats@entry=0x7f042c63e468, cb=cb@entry=
    0x55bd783f5bf0 <gen_osd_cb>, cb_ctx=cb_ctx@entry=0x7f042c63e410)
    at ../sub/osd.c:326
#8  0x000055bd783f6796 in mpgl_osd_generate (ctx=0x7f042c63e410, res=..., 
    pts=<optimized out>, stereo_mode=0, draw_flags=<optimized out>)
    at ../video/out/gpu/osd.c:339
#9  0x000055bd783ff9ba in pass_draw_osd (p=p@entry=0x7f042c64b420, 
    draw_flags=<optimized out>, pts=<optimized out>, rect=..., fbo=..., 
--Type <RET> for more, q to quit, c to continue without paging--
    cms=cms@entry=true) at ../video/out/gpu/video.c:2640
#10 0x000055bd78406c46 in gl_video_render_frame (p=0x7f042c64b420, 
    frame=frame@entry=0x7f042de65f70, fbo=..., flags=flags@entry=3)
    at ../video/out/gpu/video.c:3162
#11 0x000055bd7841bd3c in draw_frame (vo=0x55bd7a75f270, frame=0x7f042de65f70)
    at ../video/out/vo_gpu.c:87
#12 0x000055bd784197e7 in vo_render_frame_external (vo=vo@entry=0x55bd7a75f270)
    at ../video/out/vo.c:898
#13 0x000055bd7841a2ef in vo_thread (ptr=0x55bd7a75f270)
    at ../video/out/vo.c:1055
#14 0x00007f044eb12a9d in start_thread () from /usr/lib/libpthread.so.0
#15 0x00007f044cdacb23 in clone () from /usr/lib/libc.so.6
```

**Comment by vaurelios** [comment]
Found a workaround:

While subtitles position is at 0/100 theses crashes occur.

While at 100/100 it works ok.

Other positions i didn't tested.

Looks like it's a media issue (it happens with -SVA releases from RARBG/EZTV) but anyway mpv shouldn't crash.

**Comment by Dudemanguy** [comment]
Does this issue still occur?
