### ISSUE TITLE
Variable video_in in vapoursynth R41 script is not defined

### ISSUE THREAD

**Issue by rnhmjoj** [mpv-player/mpv#5388]
### mpv version and platform
0.27.0, GNU/Linux

### Reproduction steps
1. Build mpv with vapoursynth R41 
2. Run 

        $ echo "import vapoursynth; video_in" > test.vpy
        $ mpv some.video --vf vapoursynth=test.vpy:4:4

### Log file
```
Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 426, in vapoursynth.mapToDict
  File "src/cython/vapoursynth.pyx", line 1513, in vapoursynth.get_core
vapoursynth.Error: Internal environment id not set. Was get_core() called from a filter callback?
Exception ignored in: 'vapoursynth.vpy_setVariable'
Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 426, in vapoursynth.mapToDict
  File "src/cython/vapoursynth.pyx", line 1513, in vapoursynth.get_core
vapoursynth.Error: Internal environment id not set. Was get_core() called from a filter callback?
[vapoursynth] Script evaluation failed:
[vapoursynth] Python exception: name 'video_in' is not defined
[vapoursynth] 
[vapoursynth] Traceback (most recent call last):
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 1841, in vapoursynth.vpy_evaluateScript
[vapoursynth]   File "test.vpy", line 1, in <module>
[vapoursynth]     import vapoursynth; video_in
[vapoursynth] NameError: name 'video_in' is not defined
[vapoursynth] 
Video filter chain:
  [in] 1920x800 yuv420p bt.709/bt.709/bt.1886/limited SP=1.000000 CL=mpeg2/4/h264
  [vapoursynth] "vapoursynth.00" 1920x800 yuv420p bt.709/bt.709/bt.1886/limited SP=1.000000 CL=mpeg2/4/h264   <---
  [out] ???
Cannot initialize video filters.
Could not initialize video chain.
```

**Comment by shinchiro** [comment]
This is vapoursynth bug btw, not mpv. R40 works fine

**Comment by wm4** [comment]
It's also fixed in VS git.

**Comment by rnhmjoj** [comment]
Oh, I see now. Thank you.
