### ISSUE TITLE
Fail to build git master on macOS

### ISSUE THREAD

**Issue by sCreami** [mpv-player/mpv#5522]
When I try to build the git master, I'm greeted with this error:
```
../video/decode/vd_lavc.c:708:38: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    ctx->hwdec = (struct hwdec_info){0};
                                     ^
                                     {}
2 warnings generated.

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC11macOS_swift7CocoaCB", referenced from:
      objc-class-ref in macosx_application.m.26.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm on macOS 10.13.3 and I can't solve this issue myself.
Do you have any idea?

**Comment by phush0** [comment]
```
Last 15 lines from /Users/phusho/Library/Logs/Homebrew/mpv/04.python3:
../video/out/cocoa_common.m:208:20: warning: variable length array used [-Wvla]
    uint64_t values[outputs];
                   ^
1 warning generated.

[436/441] Linking build/mpv
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC11macOS_swift7CocoaCB", referenced from:
      objc-class-ref in macosx_application.m.26.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by sCreami** [comment]
@Akemi there are dozen of us! dooozeennn (probably)

**Comment by AirPort** [comment]
IIRC I had that problem yesterday, solved it by building static libmpv instead of dynamic.

**Comment by sCreami** [comment]
I tried to build the static libmpv and I seem to have multiple Swift issue

```
[ 19/410] Processing osdep/macOS_swift.o osdep/macOS_swift.h osdep/macOS_swift.swiftmodule: video/out/cocoa_cb_common.swift video/out/cocoa-cb/window.swift video/out/cocoa-cb/events_view.swift video/out/cocoa-cb/video_layer.swift osdep/macOS_mpv_helper.swift -> build/osdep/macOS_swift.o build/osdep/macOS_swift.h build/osdep/macOS_swift.swiftmodule
Waf: Leaving directory `/Users/alexis/Developer/mpv/build'
Build failed
Traceback (most recent call last):
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/Users/alexis/Developer/mpv/wscript_build.py", line 153, in swift
    return task.exec_command(cmd)
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 133, in exec_command
    return self.generator.bld.exec_command(cmd,**kw)
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Context.py", line 169, in exec_command
    ret,out,err=Utils.run_process(cmd,kw,cargs)
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Utils.py", line 570, in run_process
    return run_prefork_process(cmd,kwargs,cargs)
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Utils.py", line 517, in run_prefork_process
    raise OSError(trace)
WafError: Execution failure: /Library/Developer/CommandLineTools/usr/bin/swift -frontend -c -sdk /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -enable-objc-interop -emit-objc-header -emit-module -parse-as-library -swift-version 3 -O -module-name macOS_swift -emit-module-path /Users/alexis/Developer/mpv/build/osdep/macOS_swift.swiftmodule -import-objc-header /Users/alexis/Developer/mpv/osdep/macOS_swift_bridge.h -emit-objc-header-path /Users/alexis/Developer/mpv/build/osdep/macOS_swift.h -o /Users/alexis/Developer/mpv/build/osdep/macOS_swift.o /Users/alexis/Developer/mpv/video/out/cocoa_cb_common.swift /Users/alexis/Developer/mpv/video/out/cocoa-cb/window.swift /Users/alexis/Developer/mpv/video/out/cocoa-cb/events_view.swift /Users/alexis/Developer/mpv/video/out/cocoa-cb/video_layer.swift /Users/alexis/Developer/mpv/osdep/macOS_mpv_helper.swift -I. -I..
Traceback (most recent call last):
  File "<string>", line 28, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by AirPort** [comment]
That's probably due to https://github.com/mpv-player/mpv/pull/5517

**Comment by sCreami** [comment]
@AirPort Yep it is.

**Comment by Hamuko** [comment]
Same issue, wrote about it in #5516.

**Comment by Akemi** [comment]
i fixed the linking error with libmpv with the second commit on #5517. would be nice if you could confirm this issue fixed. also it would be nice if any other issue persist that a new issue is opened, otherwise i might lose the overview of the various issues i caused with this.

**Comment by sCreami** [comment]
The commit 8f9d1e1 doesn't fix the issue.
Actually it's even worst because I can't compile with  `--enable-libmpv-static` anymore.
I receive the same issue as without:

```~/Developer/mpv(master*) λ git --no-pager log -n2 --oneline                             alexis@Erokami
b1ddae31fe (HEAD -> master) build: fix libmpv build when swift features are build
1b80e124db (origin/master, origin/HEAD) vo_gpu: d3d11: implement tex_download()
-------------------------------------------------------------------------------
~/Developer/mpv(master*) λ ./bootstrap.py && ./waf configure && ./waf build
Found 'waf', skipping download.
…
Detected target OS:                      : os-darwin 
Checking for macOS SDK                   : /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk 
Checking for swift (Swift compiler)      : /Library/Developer/CommandLineTools/usr/bin/swift 
Checking for Swift Library               : /Library/Developer/CommandLineTools/usr/lib/swift_static/macosx 
…
Writing configuration header:                                        : config.h 
'configure' finished successfully (7.274s)
[1] 67721
Waf: Entering directory `/Users/alexis/Developer/mpv/build'
[1/1] Compiling version.sh
[ 19/215] Processing osdep/macOS_swift.o osdep/macOS_swift.h osdep/macOS_swift.swiftmodule: video/out/cocoa_cb_common.swift video/out/cocoa-cb/window.swift video/out/cocoa-cb/events_view.swift video/out/cocoa-cb/video_layer.swift osdep/macOS_mpv_helper.swift -> build/osdep/macOS_swift.o build/osdep/macOS_swift.h build/osdep/macOS_swift.swiftmodule
Waf: Leaving directory `/Users/alexis/Developer/mpv/build'
Build failed
Traceback (most recent call last):
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/Users/alexis/Developer/mpv/wscript_build.py", line 153, in swift
    return task.exec_command(cmd)
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 133, in exec_command
    return self.generator.bld.exec_command(cmd,**kw)
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Context.py", line 169, in exec_command
    ret,out,err=Utils.run_process(cmd,kw,cargs)
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Utils.py", line 570, in run_process
    return run_prefork_process(cmd,kwargs,cargs)
  File "/Users/alexis/Developer/mpv/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Utils.py", line 517, in run_prefork_process
    raise OSError(trace)
WafError: Execution failure: /Library/Developer/CommandLineTools/usr/bin/swift -frontend -c -sdk /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -enable-objc-interop -emit-objc-header -emit-module -parse-as-library -swift-version 3 -O -module-name macOS_swift -emit-module-path /Users/alexis/Developer/mpv/build/osdep/macOS_swift.swiftmodule -import-objc-header /Users/alexis/Developer/mpv/osdep/macOS_swift_bridge.h -emit-objc-header-path /Users/alexis/Developer/mpv/build/osdep/macOS_swift.h -o /Users/alexis/Developer/mpv/build/osdep/macOS_swift.o /Users/alexis/Developer/mpv/video/out/cocoa_cb_common.swift /Users/alexis/Developer/mpv/video/out/cocoa-cb/window.swift /Users/alexis/Developer/mpv/video/out/cocoa-cb/events_view.swift /Users/alexis/Developer/mpv/video/out/cocoa-cb/video_layer.swift /Users/alexis/Developer/mpv/osdep/macOS_mpv_helper.swift -I. -I..
Traceback (most recent call last):
  File "<string>", line 28, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by Akemi** [comment]
you need both commits of that PR.

**Comment by sCreami** [comment]
My bad. It does fix the issue.

**Comment by Akemi** [comment]
cool. thx for testing. hopefully this isn't a half baked fix again.
