### ISSUE TITLE
MPV becoming unresponsive after repeated 'loadfile' calls via JSON IPC

### ISSUE THREAD

**Issue by tvm1** [mpv-player/mpv#5683]
### mpv version and platform
Originally found on 0.27, also seems to be broken on master
Linux on ARMv7 (RPI 3), if needed i can test it on amd64 too.

### Reproduction steps
Start mpv with:

` mpv --idle --no-input-default-bindings --input-ipc-server /tmp/mpvsocket --log-file/tmp/mpvlog --msg-level=a=debug`

Feed loadfile commands to mpv via JSON IPC, just like this:
```
[   2.570][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/9ad7a1ee-881e-4052-a539-d83245e8962d, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=33.914196]
[   3.356][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/8444444b-01d7-4799-90ae-5bd51bbf568f, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[  52.786][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/8136c8c1-e363-4605-8b64-67bafc4b01a8, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[  73.394][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/5f81fd7d-95e2-456c-ab4d-dea1194a9cae, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 104.201][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/0a823a16-d18b-44b4-ad10-e72b7ae52a90, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 133.930][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/392d835f-054d-4719-b700-2ddc203ff6da, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 178.968][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/d229c514-99b2-4c56-ad2a-8a93e2a80f75, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 210.315][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/55f1fd88-bc20-4983-8dc7-a7f6c58985dc, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 241.603][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/9ad7a1ee-881e-4052-a539-d83245e8962d, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=32.252156]
[ 243.161][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/8444444b-01d7-4799-90ae-5bd51bbf568f, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 299.283][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/8136c8c1-e363-4605-8b64-67bafc4b01a8, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 312.688][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/ee2180a5-4c21-4f1e-bca1-0af6a6e544b7, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 344.179][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/9ad7a1ee-881e-4052-a539-d83245e8962d, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=12.990378]
[ 345.248][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/55f1fd88-bc20-4983-8dc7-a7f6c58985dc, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 377.408][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/392d835f-054d-4719-b700-2ddc203ff6da, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 421.145][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/8444444b-01d7-4799-90ae-5bd51bbf568f, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=54.84953]
[ 421.781][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/8136c8c1-e363-4605-8b64-67bafc4b01a8, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 454.207][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/9ad7a1ee-881e-4052-a539-d83245e8962d, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 462.790][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/ee2180a5-4c21-4f1e-bca1-0af6a6e544b7, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 493.960][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/8444444b-01d7-4799-90ae-5bd51bbf568f, append-play, length=100%,volume=100,geometry=1920x1080+0+0,start=4.68643]
[ 503.366][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/5f81fd7d-95e2-456c-ab4d-dea1194a9cae, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 534.754][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/0a823a16-d18b-44b4-ad10-e72b7ae52a90, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 639.889][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/55f1fd88-bc20-4983-8dc7-a7f6c58985dc, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 564.909][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/d229c514-99b2-4c56-ad2a-8a93e2a80f75, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
[ 595.870][d][cplayer] Run command: loadfile, flags=0, args=[/store//media/392d835f-054d-4719-b700-2ddc203ff6da, replace, length=100%,volume=100,geometry=1920x1080+0+0,start=0]
```
However, the same command sequence will work just fine (tested for days worth of playback) if one uses only `append-play`. This problem seems to show up only when using `replace` and seems to hint that there's some issue when `loadfile replace` gets issued at the exact time when the playlist is about to become empty and the previous video in playlist is finishing or has just finished. This situation is visible at `639.889` in linked logfile.

### Expected behavior
Mpv doesn't freeze and continues playback correctly.

### Actual behavior
Mpv will stop playback after undetermined time period (may vary between 10 minutes up to around two hours) and become unresponsive (although there's no crash). JSON IPC also becomes unresponsive, it's not possible to query property like `clock` anymore.

### Log file
[Log file](https://0x0.st/sBlB.txt)

**Comment by wm4** [comment]
Do you read from the IPC socket? If it gets full, the client thread will be blocked, although it shouldn't block the core.
Can you get thread backtraces from mpv when it's frozen?

**Comment by tvm1** [comment]
I do read from IPC socket and check for response, but if you mention this, let me go deeper.

**Comment by tvm1** [comment]
Here is thread BT after mpv becomes unresponsive.

[bt.txt](https://github.com/mpv-player/mpv/files/1855176/bt.txt)

**Comment by wm4** [comment]
Seems like the decoder is frozen:
```
Thread 1 (Thread 0x730134c0 (LWP 935)):
---Type <return> to continue, or q <return> to quit---
#0  0x761a7014 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x76d613bc <client+36>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x76d613bc <client+36>, abstime=0x0) at sem_waitcommon.c:115
#2  0x761a7158 in __new_sem_wait_slow (sem=0x76d613bc <client+36>, abstime=0x0) at sem_waitcommon.c:282
#3  0x76d4bd30 in mmal_vc_sendwait_message () from /opt/vc/lib/libmmal_vc_client.so
#4  0x76d4ea20 in mmal_vc_port_disable () from /opt/vc/lib/libmmal_vc_client.so
#5  0x76d88930 in mmal_port_disable_internal () from /opt/vc/lib/libmmal_core.so
#6  0x76d894dc in mmal_port_disable () from /opt/vc/lib/libmmal_core.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
The backtrace stops here, but since it's thread 1, it's most likely the mpv core thread, which calls into the decoder too. The backtrace probably would go into the `ffmmal_flush` and `ffmmal_stop_decoder` functions, which try to uninit the decoder and call `mmal_port_disable`.

This is consistent with spamming `loadfile` commands: they will try to initialize playback (including the decoder), but the next `loadfile` command will uninit it again, and this repeated at a higher frequency than usual.

I suggest you bring this up with the MMAL firmware devs. I actually wrote most of the FFmpeg MMAL a long time ago, and I tried my best to make it not freeze. If I missed something, I don't know which.

**Comment by wm4** [comment]
PS: yes, that means I think it's a RPI issue. Try without hw decoding, or on another platform.

**Comment by tvm1** [comment]
Let me try the same on x86.

**Comment by tvm1** [comment]
Yep, I confirm that this is RPI issue, this bug is not present x86.

**Comment by tvm1** [comment]
Could this be actually related to raspberrypi/firmware#457 which is coincidentally an issue you opened years back?
