### ISSUE TITLE
Segfault with gpu-api=vulkan and amdvlk driver

### ISSUE THREAD

**Issue by FichteFoll** [mpv-player/mpv#6084]
### mpv version and platform

```
∀ mpv --version
mpv 0.29.0-23-gd4bbfb8453 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Aug 21 11:35:23 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: n4.0.2
```

Platform: Arch Linux
Drivers: amdvlk-git r45.d7dd652 (built from git, yesterday)
Display server: xorg-server 1.20.1-1

### Reproduction steps

```
command mpv --no-config --vo=gpu --gpu-api=vulkan "https://vid.pr0gramm.com/2018/08/18/4873986412111e53.mp4"
```

### Expected behavior

Plays the video.

### Actual behavior

```
▞ command mpv --no-config --vo=gpu --gpu-api=vulkan "https://vid.pr0gramm.com/2018/08/18/4873986412111e53.mp4" --log-file=/tmp/mpv.log
Playing: https://vid.pr0gramm.com/2018/08/18/4873986412111e53.mp4
 (+) Video --vid=1 (*) (h264 934x720 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
File tags:
 Title: 321508155089952
[1]    12463 segmentation fault (core dumped)  command mpv --no-config --vo=gpu --gpu-api=vulkan  --log-file=/tmp/mpv.log
```

### Log file

<details>

```
[   0.002][v][cplayer] mpv 0.29.0-23-gd4bbfb8453 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[   0.002][v][cplayer]  built on Tue Aug 21 11:35:23 CEST 2018
[   0.002][v][cplayer] ffmpeg library versions:
[   0.002][v][cplayer]    libavutil       56.14.100
[   0.002][v][cplayer]    libavcodec      58.18.100
[   0.002][v][cplayer]    libavformat     58.12.100
[   0.002][v][cplayer]    libswscale      5.1.100
[   0.002][v][cplayer]    libavfilter     7.16.100
[   0.002][v][cplayer]    libswresample   3.1.100
[   0.002][v][cplayer] ffmpeg version: n4.0.2
[   0.002][v][cplayer] 
[   0.002][v][cplayer] Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-zsh-comp --enable-libmpv-shared
[   0.002][v][cplayer] List of enabled features: 52arch alsa asm atomics build-date caca cplayer cplugins crossc debug-build drm drmprime egl-drm egl-helpers egl-x11 fchmod ffmpeg gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm libmpv-shared librt linux-fstatfs lua optimize oss-audio plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rsound rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-wayland vaapi-x-egl vaapi-x11 vapoursynth-core vapoursynth-lazy vdpau vdpau-gl-x11 vt.h vulkan wayland wayland-protocols x11 xv zlib zsh-comp
[   0.002][v][cplayer] Command line options: '--no-config' '--vo=gpu' '--gpu-api=vulkan' 'https://vid.pr0gramm.com/2018/08/18/4873986412111e53.mp4' '--log-file=/tmp/mpv.log'
[   0.002][v][cplayer] mpv 0.29.0-23-gd4bbfb8453 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[   0.002][v][cplayer]  built on Tue Aug 21 11:35:23 CEST 2018
[   0.002][v][cplayer] ffmpeg library versions:
[   0.002][v][cplayer]    libavutil       56.14.100
[   0.002][v][cplayer]    libavcodec      58.18.100
[   0.002][v][cplayer]    libavformat     58.12.100
[   0.002][v][cplayer]    libswscale      5.1.100
[   0.002][v][cplayer]    libavfilter     7.16.100
[   0.002][v][cplayer]    libswresample   3.1.100
[   0.002][v][cplayer] ffmpeg version: n4.0.2
[   0.002][v][cplayer] 
[   0.002][v][cplayer] Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-zsh-comp --enable-libmpv-shared
[   0.002][v][cplayer] List of enabled features: 52arch alsa asm atomics build-date caca cplayer cplugins crossc debug-build drm drmprime egl-drm egl-helpers egl-x11 fchmod ffmpeg gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm libmpv-shared librt linux-fstatfs lua optimize oss-audio plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rsound rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-wayland vaapi-x-egl vaapi-x11 vapoursynth-core vapoursynth-lazy vdpau vdpau-gl-x11 vt.h vulkan wayland wayland-protocols x11 xv zlib zsh-comp
[   0.002][d][cplayer] Setting option 'config' = 'no' (flags = 8)
[   0.002][d][cplayer] Setting option 'vo' = 'gpu' (flags = 8)
[   0.002][d][cplayer] Setting option 'gpu-api' = 'vulkan' (flags = 8)
[   0.002][d][cplayer] Setting option 'log-file' = '/tmp/mpv.log' (flags = 8)
[   0.003][d][global] user path: '/tmp/mpv.log' -> '/tmp/mpv.log'
[   0.003][d][osc] Loading lua script @osc.lua...
[   0.003][d][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.003][d][stats] Loading lua script @stats.lua...
[   0.003][v][cplayer] Waiting for scripts...
[   0.003][d][stats] loading mp.defaults
[   0.003][d][ytdl_hook] loading mp.defaults
[   0.003][d][osc] loading mp.defaults
[   0.004][d][ytdl_hook] loading @ytdl_hook.lua
[   0.004][d][osc] loading @osc.lua
[   0.004][d][stats] loading @stats.lua
[   0.004][d][ytdl_hook] reading options for ytdl_hook 
[   0.004][v][ytdl_hook] script-opts/ytdl_hook.conf not found. 
[   0.004][v][ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[   0.005][d][stats] reading options for stats 
[   0.005][v][stats] script-opts/stats.conf not found. 
[   0.005][v][stats] lua-settings/stats.conf not found. 
[   0.006][d][cplayer] Run command: define-section, flags=0, args=[input_stats, i script-binding stats/display-stats
[   0.006][d][cplayer] , default]
[   0.006][d][cplayer] Run command: enable-section, flags=0, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[   0.006][d][cplayer] Run command: define-section, flags=0, args=[input_forced_stats, , force]
[   0.006][d][cplayer] Run command: enable-section, flags=0, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[   0.006][d][cplayer] Run command: define-section, flags=0, args=[input_stats, I script-binding stats/display-stats-toggle
[   0.006][d][cplayer] i script-binding stats/display-stats
[   0.006][d][cplayer] , default]
[   0.006][d][cplayer] Run command: enable-section, flags=0, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[   0.006][d][cplayer] Run command: define-section, flags=0, args=[input_forced_stats, , force]
[   0.006][d][cplayer] Run command: enable-section, flags=0, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[   0.006][d][cplayer] Run command: define-section, flags=0, args=[input_stats, I script-binding stats/display-stats-toggle
[   0.006][d][cplayer] i script-binding stats/display-stats
[   0.006][d][cplayer] , default]
[   0.006][d][cplayer] Run command: enable-section, flags=0, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[   0.006][d][cplayer] Run command: define-section, flags=0, args=[input_forced_stats, , force]
[   0.006][d][cplayer] Run command: enable-section, flags=0, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[   0.006][d][cplayer] Run command: define-section, flags=0, args=[input_stats, I script-binding stats/display-stats-toggle
[   0.006][d][cplayer] i script-binding stats/display-stats
[   0.006][d][cplayer] , default]
[   0.006][d][cplayer] Run command: enable-section, flags=0, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[   0.006][d][cplayer] Run command: define-section, flags=0, args=[input_forced_stats, , force]
[   0.006][d][cplayer] Run command: enable-section, flags=0, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[   0.007][d][osc] reading options for osc 
[   0.007][v][osc] script-opts/osc.conf not found. 
[   0.007][v][osc] lua-settings/osc.conf not found. 
[   0.007][d][cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[   0.007][d][cplayer] mouse_leave script-binding osc/__keybinding2
[   0.007][d][cplayer] , force]
[   0.007][d][cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[   0.007][d][cplayer] Run command: define-section, flags=0, args=[input, mbtn_left script-binding osc/__keybinding3
[   0.007][d][cplayer] shift+mbtn_left script-binding osc/__keybinding4
[   0.007][d][cplayer] mbtn_right script-binding osc/__keybinding5
[   0.007][d][cplayer] wheel_up script-binding osc/__keybinding6
[   0.007][d][cplayer] wheel_down script-binding osc/__keybinding7
[   0.007][d][cplayer] mbtn_left_dbl ignore
[   0.007][d][cplayer] shift+mbtn_left_dbl ignore
[   0.007][d][cplayer] mbtn_right_dbl ignore
[   0.007][d][cplayer] , force]
[   0.007][d][cplayer] Run command: enable-section, flags=0, args=[input, ]
[   0.007][d][cplayer] Run command: define-section, flags=0, args=[input_osc, , default]
[   0.007][d][cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]
[   0.007][d][cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[   0.007][d][cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]
[   0.007][v][cplayer] Done loading scripts.
[   0.007][d][global] config path: 'watch_later' -> '-'
[   0.007][d][global] config path: 'watch_later' -> '-'
[   0.007][i][cplayer] Playing: https://vid.pr0gramm.com/2018/08/18/4873986412111e53.mp4
[   0.007][v][cplayer] Running hook: ytdl_hook/on_load
[   0.007][v][ytdl_hook] ytdl:// hook 
[   0.007][v][ytdl_hook] not a ytdl:// url 
[   0.007][d][osc] osc_init 
[   0.007][v][ffmpeg] Opening https://vid.pr0gramm.com/2018/08/18/4873986412111e53.mp4
[   0.008][d][cplayer] Run command: disable-section, flags=0, args=[input]
[   0.008][v][osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.8.8 (COMPLEX)
[   0.008][v][osd/libass] Setting up fonts...
[   0.015][v][osd/libass] Using font provider fontconfig
[   0.015][v][osd/libass] Done.
[   0.238][v][ffmpeg] Mime-type: 'video/mp4'
[   0.238][d][ffmpeg] Stream opened successfully.
[   0.238][v][cache] no backbuffer needed
[   0.238][v][cache] Cache size set to 5965 KiB (32 KiB backbuffer)
[   0.238][v][demux] Trying demuxers for level=normal.
[   0.239][d][demux] Trying demuxer: disc (force-level: normal)
[   0.239][d][demux] Trying demuxer: edl (force-level: normal)
[   0.239][d][demux] Trying demuxer: cue (force-level: normal)
[   0.239][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.240][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.240][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.241][d][demux] Trying demuxer: libarchive (force-level: normal)
[   0.241][d][demux] Trying demuxer: rar (force-level: normal)
[   0.242][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.245][v][lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[   0.284][v][demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[   0.284][v][cache] blocking for STREAM_CTRL 6
[   0.289][v][cplayer] Opening done: https://vid.pr0gramm.com/2018/08/18/4873986412111e53.mp4
[   0.292][v][cplayer] Running hook: ytdl_hook/on_preloaded
[   0.292][v][lavf] select track 0
[   0.292][v][lavf] select track 1
[   0.292][i][cplayer]  (+) Video --vid=1 (*) (h264 934x720 25.000fps)
[   0.292][i][cplayer]  (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
[   0.292][i][display-tags] File tags:
[   0.292][i][display-tags]  Title: 321508155089952
[   0.293][v][vo/gpu] Probing for best GPU context.
[   0.293][v][vo/gpu/vulkan] Initializing GPU context 'waylandvk'
[   0.293][v][vo/gpu/vulkan] Creating instance with extensions:
[   0.293][v][vo/gpu/vulkan]     VK_KHR_surface
[   0.293][v][vo/gpu/vulkan]     VK_KHR_wayland_surface
```

</details>

**Comment by FichteFoll** [comment]
Realized I forgot to include a core dump while I was outside.

[core.mpv.1000.zip](https://github.com/mpv-player/mpv/files/2307872/core.mpv.1000.zip)

**Comment by haasn** [comment]
I just realized, the core doesn't help me unless I have your exact binary + dependencies. Can you post a backtrace? (Assuming you're using `coredumpctl`, it would be `coredumpctl gdb` and then `bt full`)

**Comment by FichteFoll** [comment]
Had to rebuild without stripped symbols. Here's the stack trace of a new coredump I just created with the latest mpv and amdvlk master:

```
#0  0x00007f9470be69b5 in Pal::AddrMgr::Init() () from /usr/lib/amdvlk64.so
No symbol table info available.
#1  0x00007f9470bf7d53 in Pal::Device::HwlEarlyInit() () from /usr/lib/amdvlk64.so
No symbol table info available.
#2  0x00007f9470a39908 in Pal::Device::EarlyInit(Pal::HwIpLevels const&) [clone .constprop.778] () from /usr/lib/amdvlk64.so
No symbol table info available.
#3  0x00007f9470bd401b in Pal::Linux::Device::EarlyInit(Pal::HwIpLevels const&) () from /usr/lib/amdvlk64.so
No symbol table info available.
#4  0x00007f9470bc5523 in Pal::Linux::Platform::ReQueryDevices() () from /usr/lib/amdvlk64.so
No symbol table info available.
#5  0x00007f9470be9259 in Pal::Platform::Init() () from /usr/lib/amdvlk64.so
No symbol table info available.
#6  0x00007f9470a36a57 in vk::Instance::Init(VkApplicationInfo const*) [clone .constprop.873] () from /usr/lib/amdvlk64.so
No symbol table info available.
#7  0x00007f9470c190e1 in vk::Instance::Create(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**) () from /usr/lib/amdvlk64.so
No symbol table info available.
#8  0x00007f949810311e in ?? () from /usr/lib/libvulkan.so.1
No symbol table info available.
#9  0x00007f9498106d19 in ?? () from /usr/lib/libvulkan.so.1
No symbol table info available.
#10 0x00007f949810adfe in vkCreateInstance () from /usr/lib/libvulkan.so.1
No symbol table info available.
#11 0x000055a1b3eb3de8 in mpvk_instance_init (vk=vk@entry=0x7f946c2c0d90, log=<optimized out>, surf_ext_name=surf_ext_name@entry=0x55a1b3f1a4a0 "VK_KHR_wayland_surface", debug=<optimized out>) at ../video/out/vulkan/utils.c:216
        info = {sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO, pNext = 0x0, flags = 0, pApplicationInfo = 0x0, enabledLayerCount = 0, ppEnabledLayerNames = 0x0, enabledExtensionCount = 2, ppEnabledExtensionNames = 0x7f94734778c0}
        extensions = {0x55a1b3f1c7ac "VK_KHR_surface", 0x55a1b3f1a4a0 "VK_KHR_wayland_surface", 0x55a1b3f1c7bb "VK_EXT_debug_report"}
        debugExtensionCount = 1
        res = <optimized out>
#12 0x000055a1b3ead420 in wayland_vk_init (ctx=0x7f946c0c1230) at ../video/out/vulkan/context_wayland.c:44
        p = 0x7f946c2c0d90
        vk = 0x7f946c2c0d90
        msgl = 5
        wlinfo = {sType = 1814418464, pNext = 0x874b156db40fc400, flags = 3019012652, display = 0x55a1b3ec3ba9 <ta_xstrdup+9>, surface = 0x7f946c560130}
        res = <optimized out>
#13 0x000055a1b3e7c651 in ra_ctx_create (vo=vo@entry=0x55a1b46445f0, context_type=<optimized out>, context_name=<optimized out>, opts=...) at ../video/out/gpu/context.c:193
        ctx = 0x7f946c0c1230
        i = <optimized out>
        api_auto = false
        ctx_auto = <optimized out>
        old_probing = false
#14 0x000055a1b3ea3294 in preinit (vo=0x55a1b46445f0) at ../video/out/vo_gpu.c:280
        p = 0x55a1b466af60
        alpha_mode = 3
        opts = {allow_sw = 0, want_alpha = 0, debug = 0, probing = false, swapchain_depth = 3}
        __PRETTY_FUNCTION__ = "preinit"
#15 0x000055a1b3ea1083 in vo_thread (ptr=0x55a1b46445f0) at ../video/out/vo.c:1039
        vo = <optimized out>
        in = 0x55a1b45fc200
        vo_paused = false
        r = <optimized out>
#16 0x00007f9492893a9d in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#17 0x00007f94927c3a43 in clone () from /usr/lib/libc.so.6
No symbol table info available.
```

I can also provide the log of that if needed.

**Comment by haasn** [comment]
Don't see anything wrong with mpv's invocation there, and it segfaults inside the very first vulkan call; the one that creates the vulkan instance itself. File an amdvlk bug.

**Comment by FichteFoll** [comment]
Just a heads-up that this works now with a 4.19 kernel, probably due to https://github.com/GPUOpen-Drivers/AMDVLK/issues/50#issuecomment-419015191
