### ISSUE TITLE
SEGFAULT with --opengl-es=yes and --opengl-pbo=yes

### ISSUE THREAD

**Issue by xantoz** [mpv-player/mpv#6197]
### mpv version and platform
mpv 0.29.0

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Run with --opengl-es=yes and --opengl-pbo=yes with either --gpu-context=x11egl or --gpu-context=drm (other EGL contexts likely affected as well) then spam alternately o and i

### Expected behavior
Doesn't SEGFAULT

### Actual behavior
SEGFAULTs

### Log file
[mpv-sucks2.log](https://github.com/mpv-player/mpv/files/2461825/mpv-sucks2.log)
[mpv-sucks3.log](https://github.com/mpv-player/mpv/files/2461826/mpv-sucks3.log)

**Comment by xantoz** [comment]
Backtrace:
```(gdb) run --gpu-context=x11egl --opengl-es=yes  --opengl-pbo=yes ~/Video/*mkv
Starting program: /usr/bin/mpv --gpu-context=x11egl --opengl-es=yes  --opengl-pbo=yes ~/Video/*mkv
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe27b7700 (LWP 1084)]
[New Thread 0x7fffe1fb6700 (LWP 1085)]
[New Thread 0x7fffe17b5700 (LWP 1086)]
[New Thread 0x7fffe0fb4700 (LWP 1087)]
[New Thread 0x7fffdbfff700 (LWP 1088)]
[New Thread 0x7fffdb7fe700 (LWP 1089)]
[New Thread 0x7fffdaffd700 (LWP 1090)]
Playing: /home/tewi_inaba/Video/60.000.mkv
[New Thread 0x7fffda7fc700 (LWP 1092)]
[New Thread 0x7fffda7fc700 (LWP 1097)]
[Thread 0x7fffda7fc700 (LWP 1092) exited]
 (+) Video --vid=1 (*) (h264 1920x1080 60.000fps)
[New Thread 0x7fffd9ffb700 (LWP 1098)]
[New Thread 0x7fffd97fa700 (LWP 1099)]
[New Thread 0x7fffbffff700 (LWP 1102)]
[vo/gpu/opengl] Could not create EGL context for Desktop OpenGL!
Using hardware decoding (vaapi).
VO: [gpu] 1920x1080 vaapi[nv12]
V: 00:00:00 / 00:02:25 (0%) DS: 1.000/1
[osd/libass] fontselect: Using default font family: (Source Sans Pro, 400, 0) -> /usr/share/fonts/dejavu/DejaVuSans.ttf, 0, DejaVuSans
[osd/libass] fontselect: Using default font family: (Source Sans Pro, 700, 0) -> /usr/share/fonts/dejavu/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold

Thread 11 "mpv/vo" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd9ffb700 (LWP 1098)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000555555660a93 in gl_buf_destroy (ra=<optimized out>, buf=0x7fffc49b3e00) at ../video/out/opengl/ra_gl.c:545
#2  0x00005555556462d2 in ra_buf_free (ra=ra@entry=0x7fffc450cf50, buf=0x7fffc49b4050) at ../video/out/gpu/ra.c:47
#3  0x000055555564b408 in ra_buf_pool_uninit (ra=0x7fffc450cf50, pool=pool@entry=0x7fffc49b35a0) at ../video/out/gpu/utils.c:45
#4  0x00005555556611ea in gl_tex_destroy (ra=<optimized out>, tex=0x7fffc49b3520) at ../video/out/opengl/ra_gl.c:241
#5  0x00005555556462a2 in ra_tex_free (ra=ra@entry=0x7fffc450cf50, tex=tex@entry=0x7fffc45ab728) at ../video/out/gpu/ra.c:35
#6  0x000055555564545f in upload_osd (imgs=0x7fffd9ff9a10, osd=0x7fffc45ab720, ctx=0x7fffc459d750) at ../video/out/gpu/osd.c:140
#7  gen_osd_cb (pctx=pctx@entry=0x7fffc459d750, imgs=imgs@entry=0x7fffd9ff9a10) at ../video/out/gpu/osd.c:195
#8  0x000055555562eb14 in osd_draw (osd=0x55555599f0c0, res=..., video_pts=0.73299999999999998, draw_flags=0, formats=formats@entry=0x7fffc459d7a8, cb=cb@entry=0x555555645320 <gen_osd_cb>, cb_ctx=cb_ctx@entry=0x7fffc459d750)
    at ../sub/osd.c:329
#9  0x0000555555645edf in mpgl_osd_generate (ctx=0x7fffc459d750, res=..., pts=<optimized out>, stereo_mode=0, draw_flags=<optimized out>) at ../video/out/gpu/osd.c:339
#10 0x000055555564ec19 in pass_draw_osd (p=p@entry=0x7fffc45258d0, draw_flags=<optimized out>, pts=<optimized out>, rect=..., fbo=..., cms=cms@entry=true) at ../video/out/gpu/video.c:2634
#11 0x0000555555655f12 in gl_video_render_frame (p=0x7fffc45258d0, frame=frame@entry=0x555555a05770, fbo=..., flags=flags@entry=3) at ../video/out/gpu/video.c:3156
#12 0x0000555555667b6b in draw_frame (vo=0x5555559a70f0, frame=0x555555a05770) at ../video/out/vo_gpu.c:87
#13 0x0000555555665712 in vo_render_frame_external (vo=vo@entry=0x5555559a70f0) at ../video/out/vo.c:898
#14 0x0000555555666018 in vo_thread (ptr=0x5555559a70f0) at ../video/out/vo.c:1055
#15 0x00007ffff34d48ea in start_thread (arg=0x7fffd9ffb700) at pthread_create.c:465
#16 0x00007fffef8f561f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 

```

**Comment by xantoz** [comment]
Other useful information:
media-libs/mesa-18.1.9

**Comment by haasn** [comment]
This patch should fix it:

```diff
diff --git a/video/out/opengl/ra_gl.c b/video/out/opengl/ra_gl.c
index 7112464e87..70bd9f61aa 100644
--- a/video/out/opengl/ra_gl.c
+++ b/video/out/opengl/ra_gl.c
@@ -542,7 +542,9 @@ static void gl_buf_destroy(struct ra *ra, struct ra_buf *buf)
     GL *gl = ra_gl_get(ra);
     struct ra_buf_gl *buf_gl = buf->priv;
 
-    gl->DeleteSync(buf_gl->fence);
+    if (buf_gl->fence)
+        gl->DeleteSync(buf_gl->fence);
+
     if (buf->data) {
         gl->BindBuffer(buf_gl->target, buf_gl->buffer);
         gl->UnmapBuffer(buf_gl->target);
```

No idea how the hell that never got hit before.

**Comment by xantoz** [comment]
Confirmed your patch fixes the bug.
