### ISSUE TITLE
It crashes if I switch the audio channel with sofalizer.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6932]
It doesn't happen if I switch from acopy to anull, nor without af to sofalizer.
### mpv version and platform
```
mpv 0.29.0-385-g6e6ec33168 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.35.100
   libavcodec      58.56.101
   libavformat     58.32.104
   libswscale      5.6.100
   libavfilter     7.58.102
   libswresample   3.6.100
ffmpeg version: N-94826-g558265d4bc
```
### Reproduction steps
1. Add this in my mpv.conf.
```
[multichannel]
profile-desc=cond:get('audio-params/channel-count', -math.huge) > 2
af=sofalizer=sofa=/home/laichiaheng/.config/mpv/ClubFritz4.sofa:interpolate=true:radius=3:gain=15
volume=100
[stereo]
profile-desc=cond:get('audio-params/channel-count', -math.huge) <= 2
af=anull #or acopy
volume=70
```
2. Switch the audio from stereo to DTS-HDMA.
### Expected behavior
Switch from anull/acopy to sofalizer.
### Actual behavior
It crashes.
### Log file
https://0x0.st/zJ5x.txt

**Comment by richardpl** [comment]
I see no crash log.

**Comment by richardpl** [comment]
If I switch from stereo profile to multichannel profile during runtime i can reproduce it.

**Comment by laichiaheng** [comment]
@richardpl Is it possible to be fixed?

**Comment by richardpl** [comment]
There is workaround, do not use profile but commands to toggle filter on/of.

**Comment by wm4** [comment]
Assuming bug in ffmpeg, closing.

**Comment by richardpl** [comment]
This is mpv bug.

**Comment by wm4** [comment]
Provide backtrace with debugging infos.

**Comment by laichiaheng** [comment]
@wm4 
```
(gdb) thread apply all backtrace

Thread 91 (Thread 0x7ffefb7f6700 (LWP 27973)):
#0  0x00007ffff60e1c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x0000555555734e9c in  ()
#2  0x00007ffff60db4cf in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007ffff589c2d3 in clone () at /usr/lib/libc.so.6

Thread 90 (Thread 0x7ffefbff7700 (LWP 27972)):
#0  0x00007ffff58919ef in poll () at /usr/lib/libc.so.6
#1  0x00007ffff7c63c14 in  () at /usr/lib/libpulse.so.0
#2  0x00007ffff7c71059 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007ffff7c7b301 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007ffff7c7b3b1 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007ffff7c6b61e in  () at /usr/lib/libpulse.so.0
#6  0x00007ffff55ccd1c in  () at /usr/lib/pulseaudio/libpulsecommon-13.0.so
#7  0x00007ffff60db4cf in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff589c2d3 in clone () at /usr/lib/libc.so.6

Thread 89 (Thread 0x7ffefc7f8700 (LWP 27971)):
#0  0x00007ffff60e1c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x0000555556568c9c in  ()
#2  0x00007ffff60db4cf in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007ffff589c2d3 in clone () at /usr/lib/libc.so.6

Thread 88 (Thread 0x7ffefcff9700 (LWP 27970)):
#0  0x00007ffff60e1c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x0000555556568c9c in  ()
#2  0x00007ffff60db4cf in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007ffff589c2d3 in clone () at /usr/lib/libc.so.6

Thread 87 (Thread 0x7ffefd7fa700 (LWP 27969)):
#0  0x00007ffff60e1c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x0000555556568c9c in  ()
#2  0x00007ffff60db4cf in start_thread () at /usr/lib/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--

```

**Comment by wm4** [comment]
There's neither a crash nor debugging infos.

**Comment by laichiaheng** [comment]
@richardpl Help!
