### ISSUE TITLE
rst2pdf failure

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#7505]
### Important Information
Almost latest git master (git-2020-03-03-24acddb
Ubuntu 18.04
rst2pdf 0.93-6
Which version of mpv introduced the problem
https://github.com/mpv-player/mpv/commit/679e4108f29db061e85687af18f0e013c067f59b

Fails with this at end
```
<line><strong>mpv</strong> [options] [file|URL|PLAYLIST|-]</line> line
<line><strong>mpv</strong> [options] files</line> line
<line>a show-text "command 1" ; show-text "command 2"</line> line
<line>a-b-c show-text "command run after a, b, c have been pressed"</line> line
<line>Displays current media-title, filename, or custom title</line> line
<line>Shows current cache fill status</line> line
<line>Shows current playback position timestamp</line> line
<line>Indicates current playback position and position of chapters</line> line
<line>Shows remaining playback time timestamp</line> line
<line>Displays selected track and amount of available tracks</line> line

Traceback (most recent call last):
  File "/usr/bin/rst2pdf", line 11, in <module>
    load_entry_point('rst2pdf===0.93.dev-r0', 'console_scripts', 'rst2pdf')()
  File "/usr/lib/python2.7/dist-packages/rst2pdf/createpdf.py", line 1495, in main
    compressed=options.compressed)
  File "/usr/lib/python2.7/dist-packages/rst2pdf/createpdf.py", line 653, in createPdf
    pdfdoc.multiBuild(elements)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 1056, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 969, in build
    self.handle_flowable(flowables)
  File "/usr/lib/python2.7/dist-packages/rst2pdf/createpdf.py", line 801, in handle_flowable
    self.handle_frameEnd()
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 683, in handle_frameEnd
    self.handle_pageEnd()
  File "/usr/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 629, in handle_pageEnd
    raise LayoutError(ident)
reportlab.platypus.doctemplate.LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.

Waf: Leaving directory `/home/doug/Desktop/tttttt/mpv/build'
Build failed
 -> task in 'rst2pdf' failed with exit status 1: 
	{task 140089769515472: rst2pdf mpv.rst -> mpv.pdf}
' /usr/bin/rst2pdf -c -b 1 --repeat-table-rows ../DOCS/man/mpv.rst -o DOCS/man/mpv.pdf '
```

This stuff is incomprehensible to me, the fail goes away if I remove the :always:   Same as ``yes`` (for compatibility) line..

**Comment by lachs0r** [comment]
This is a reportlab/rst2pdf bug we’ve run into a couple times, seemingly related to tables. Our workaround was to change things in the manpage until reportlab is happy — until we got tired of it and disabled it by default. A few distros have also stopped shipping rst2pdf.

Afraid we have no way to fix this reliably. Sorry.
