### ISSUE TITLE
mpv build fails on stream/stream_lavf.c on macOS

### ISSUE THREAD

**Issue by sclsj** [mpv-player/mpv#7788]
### mpv version and platform versions
macOS High Sierra 10.13.6
cloned from git yesterday
build tools from XCode
dependencies installed via Homebrew
### Reproduction steps
waf configure --enable-libmpv-static --enable-static-build --enable-html-build --enable-pdf-build --enable-swift-static --enable-dvdnav --enable-cdda --enable-dvbin --enable-sdl2 --enable-openal
waf
### Expected behavior
Compiles successfully
### Actual behavior
[ 38/435] Compiling stream/stream_lavf.c
In file included from ../stream/stream_dvb.c:59:
../stream/dvbin.h:23:10: fatal error: 'linux/dvb/dmx.h' file not found
#include <linux/dvb/dmx.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.

Traceback (most recent call last):
  File "/usr/local/bin/rst2pdf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/rst2pdf/createpdf.py", line 1497, in main
    compressed=options.compressed)
  File "/usr/local/lib/python3.7/site-packages/rst2pdf/createpdf.py", line 643, in createPdf
    pdfdoc.multiBuild(elements)
  File "/usr/local/lib/python3.7/site-packages/reportlab/platypus/doctemplate.py", line 1143, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/usr/local/lib/python3.7/site-packages/reportlab/platypus/doctemplate.py", line 1056, in build
    self.handle_flowable(flowables)
  File "/usr/local/lib/python3.7/site-packages/rst2pdf/createpdf.py", line 791, in handle_flowable
    self.handle_frameEnd()
  File "/usr/local/lib/python3.7/site-packages/reportlab/platypus/doctemplate.py", line 709, in handle_frameEnd
    self.handle_pageEnd()
  File "/usr/local/lib/python3.7/site-packages/reportlab/platypus/doctemplate.py", line 651, in handle_pageEnd
    raise LayoutError(ident)
reportlab.platypus.doctemplate.LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.

Waf: Leaving directory `/private/var/root/mpv/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
 -> task in 'rst2pdf' failed with exit status 1 (run with -v to display more information)
### Log file
[config.log](https://github.com/mpv-player/mpv/files/4709039/config.log)

**Comment by Akemi** [comment]
was dvbin even ever supported on macOS? i don't really keep up the the DVB support in mpv. if it was supported what release/commit did break it?

**Comment by wm4** [comment]
Most definitely not. This happens because ``--enable-dvbin`` was passed. Don't do that.
