### ISSUE TITLE
Youtube-dl [ytdl_hook] Traceback

### ISSUE THREAD

**Issue by Juliaria08** [mpv-player/mpv#8354]
### Important Information

Provide following Information:
- mpv 
```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: n4.3.1
```
- Linux Distribution and Version
```
$ uname -a 
Linux art 5.9.10-artix1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 17:02:30 +0000 x86_64 GNU/Linux
$ neofetch
[julian@art ~]$ neofetch 
--------------------------------------   julian@art 
--------------------------------------   ---------- 
--------------------------------------   OS: Bedrock Li 
---\\\\\\\\\\\\-----------------------   Host: N141CU 
----\\\      \\\----------------------   Kernel: 5.9.10 
-----\\\      \\\---------------------   Uptime: 1 day, 
------\\\      \\\\\\\\\\\\\\\\\------   Packages: 1391 
-------\\\                    \\\-----   Shell: zsh 5.8 
--------\\\                    \\\----   Resolution: 19 
---------\\\        ______      \\\---   WM: bspwm 
----------\\\                   ///---   Theme: Sweet-D 
-----------\\\                 ///----   Icons: candy-i 
------------\\\               ///-----   Terminal: st 
-------------\\\////////////////------   Terminal Font: 
--------------------------------------   CPU: Intel i7- 
--------------------------------------   GPU: Intel UHD 
--------------------------------------   Memory: 1332Mi 
[julian@art ~]$ neofetch 
--------------------------------------   julian@art 
--------------------------------------   ---------- 
--------------------------------------   OS: Bedrock Linux 0.7. 
---\\\\\\\\\\\\-----------------------   Host: N141CU 
----\\\      \\\----------------------   Kernel: 5.9.10-artix1- 
-----\\\      \\\---------------------   Uptime: 1 day, 55 mins 
------\\\      \\\\\\\\\\\\\\\\\------   Packages: 1391 (pacman 
-------\\\                    \\\-----   Shell: zsh 5.8 
--------\\\                    \\\----   Resolution: 1920x1080 
---------\\\        ______      \\\---   WM: bspwm 
----------\\\                   ///---   Theme: Sweet-Dark [GTK 
-----------\\\                 ///----   Icons: candy-icons [GT 
------------\\\               ///-----   Terminal: st 
-------------\\\////////////////------   Terminal Font: JoyPixe 
--------------------------------------   CPU: Intel i7-10510U ( 
--------------------------------------   GPU: Intel UHD Graphic 
--------------------------------------   Memory: 1325MiB / 31804MiB 
[julian@art ~]$ neofetch 
--------------------------------------   julian@art 
--------------------------------------   ---------- 
--------------------------------------   OS: Bedrock Linux 0.7.19 Poki x86_64 
---\\\\\\\\\\\\-----------------------   Host: N141CU 
----\\\      \\\----------------------   Kernel: 5.9.10-artix1-1 
-----\\\      \\\---------------------   Uptime: 1 day, 55 mins 
------\\\      \\\\\\\\\\\\\\\\\------   Packages: 1391 (pacman), 321 (dpkg), 619 (rpm), 
-------\\\                    \\\-----   Shell: zsh 5.8 
--------\\\                    \\\----   Resolution: 1920x1080 
---------\\\        ______      \\\---   WM: bspwm 
----------\\\                   ///---   Theme: Sweet-Dark [GTK2/3] 
-----------\\\                 ///----   Icons: candy-icons [GTK2/3] 
------------\\\               ///-----   Terminal: st 
-------------\\\////////////////------   Terminal Font: JoyPixels 
--------------------------------------   CPU: Intel i7-10510U (8) @ 4.900GHz 
--------------------------------------   GPU: Intel UHD Graphics 
--------------------------------------   Memory: 1328MiB / 31804MiB 
$ neofetch 
OS: Bedrock Linux 0.7.19 Poki x86_64 
Host: N141CU 
Kernel: 5.9.10-artix1-1
```
- Source of the mpv binary `pacman`
- If known which version of mpv introduced the problem
- Window Manager and version
```
WM: bspwm
WM-Ver: 0.9.10
```
- GPU driver and version
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
stepping	: 12
microcode	: 0xc6
cpu MHz		: 1979.772
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds
bogomips	: 4601.60
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
stepping	: 12
microcode	: 0xc6
cpu MHz		: 976.177
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds
bogomips	: 4601.60
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
stepping	: 12
microcode	: 0xc6
cpu MHz		: 810.694
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds
bogomips	: 4601.60
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
stepping	: 12
microcode	: 0xc6
cpu MHz		: 883.211
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds
bogomips	: 4601.60
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
stepping	: 12
microcode	: 0xc6
cpu MHz		: 812.506
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds
bogomips	: 4601.60
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
stepping	: 12
microcode	: 0xc6
cpu MHz		: 873.485
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds
bogomips	: 4601.60
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
stepping	: 12
microcode	: 0xc6
cpu MHz		: 811.424
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds
bogomips	: 4601.60
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
stepping	: 12
microcode	: 0xc6
cpu MHz		: 846.653
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds
bogomips	: 4601.60
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

### Reproduction steps

Still with --no-config fails

```
$ mpv --no-config 'https://www.youtube.com/watch?v=oGYppxV-kFE'
```
### Actual behavior

Split out this error
```
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "/usr/bin/youtube-dl", line 33, in <module>
[ytdl_hook]     sys.exit(load_entry_point('youtube-dl==2020.11.29', 'console_scripts', 'youtube-dl')())
[ytdl_hook]   File "/usr/bin/youtube-dl", line 22, in importlib_load_entry_point
[ytdl_hook]     for entry_point in distribution(dist_name).entry_points
[ytdl_hook]   File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
[ytdl_hook]     return Distribution.from_name(distribution_name)
[ytdl_hook]   File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
[ytdl_hook]     raise PackageNotFoundError(name)
[ytdl_hook] importlib.metadata.PackageNotFoundError: youtube-dl
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.
```

### Log file

https://0x0.st/i7f1.txt

**Comment by CounterPillow** [comment]
Your youtube-dl installaton appears to be broken.

**Comment by Juliaria08** [comment]
It is the latest version

**Comment by Juliaria08** [comment]
But is broken
```
[julian@art ~]$ youtube-dl --version 
Traceback (most recent call last): 
  File "/usr/bin/youtube-dl", line 33, in <module> 
    sys.exit(load_entry_point('youtube-dl==2020.11.29', 'console_scripts', 'youtube-dl')()) 
  File "/usr/bin/youtube-dl", line 22, in importlib_load_entry_point 
    for entry_point in distribution(dist_name).entry_points 
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution 
    return Distribution.from_name(distribution_name) 
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name 
    raise PackageNotFoundError(name) 
importlib.metadata.PackageNotFoundError: youtube-dl 
```

**Comment by Juliaria08** [comment]
I maked a issue on [youtube-dl](https://github.com/ytdl-org/youtube-dl/issues/27282)

**Comment by CounterPillow** [comment]
pretty sure this isn't a youtube-dl issue but rather and more likely that you're running a different python version than the one youtube-dl was installed for. My guess is based on the recent release of python 3.9.

**Comment by Juliaria08** [comment]
> pretty sure this isn't a youtube-dl issue but rather and more likely that you're running a different python version than the one youtube-dl was installed for. My guess is based on the recent release of python 3.9. This can happen if you're on a rolling release distro that doesn't support partial upgrades, but do a partial upgrade of youtube-dl without upgrading python as well.

With python upgrated it works wiout the aur package.
