### ISSUE TITLE
build:  Raspberry Pi without EGL crashes waf

### ISSUE THREAD

**Issue by matoro** [mpv-player/mpv#9215]
### mpv version and platform versions

mpv 0.33.1 on armv6j-unknown-linux-gnueabihf

### Reproduction steps

I'm attempting to create a headless build to run on my Raspberry Pi Zero W that displays directly to the framebuffer, without a graphics driver.  Unfortunately, waf crashes in the configure stage when passing the corresponding options (using Gentoo ebuild flags `[raspberry-pi,-egl]`).  The full waf configure line is as follows:

```
'CCFLAGS=-O3 -march=armv6j -mfpu=vfp -mfloat-abi=hard -O2 -pipe -march=armv6j -pipe -I/opt/vc/include' 'LINKFLAGS=-O3 -march=armv6j -mfpu=vfp -mfloat-abi=hard -O2 -pipe -march=armv6j -pipe -I/opt/vc/include -Wl,-O1 -Wl,--as-needed -L/opt/vc/lib' 'PKGCONFIG=armv6j-unknown-linux-gnueabihf-pkg-config' '/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/waf' '--prefix=/usr' '--docdir=/usr/share/doc/mpv-0.33.1-r1' '--htmldir=/usr/share/doc/mpv-0.33.1-r1/html' '--libdir=/usr/lib' '--confdir=/etc/mpv' '--disable-libmpv-shared' '--disable-libmpv-static' '--disable-static-build' '--disable-optimize' '--disable-debug-build' '--disable-html-build' '--disable-pdf-build' '--enable-manpage-build' '--disable-cplugins' '--disable-test' '--enable-iconv' '--disable-lua' '--disable-javascript' '--enable-zlib' '--disable-libbluray' '--disable-dvdnav' '--disable-cdda' '--enable-uchardet' '--disable-rubberband' '--disable-lcms2' '--disable-vapoursynth' '--disable-libarchive' '--enable-libavdevice' '--disable-sdl2' '--enable-pulse' '--disable-jack' '--disable-openal' '--disable-opensles' '--enable-alsa' '--disable-coreaudio' '--disable-cocoa' '--disable-drm' '--disable-gbm' '--disable-wayland-scanner' '--disable-wayland-protocols' '--disable-wayland' '--disable-x11' '--disable-xv' '--disable-gl-cocoa' '--disable-gl-x11' '--disable-egl-x11' '--disable-egl-drm' '--disable-gl-wayland' '--disable-vdpau' '--disable-vdpau-gl-x11' '--disable-vaapi' '--disable-vaapi-x11' '--disable-vaapi-wayland' '--disable-vaapi-drm' '--disable-caca' '--disable-jpeg' '--disable-shaderc' '--disable-libplacebo' '--enable-rpi' '--disable-plain-gl' '--disable-vulkan' '--disable-sdl2-gamepad' '--disable-cuda-hwaccel' '--disable-cuda-interop' '--disable-dvbin' '--disable-zimg' '--disable-android' '--disable-egl-android' '--disable-uwp' '--disable-audiounit' '--disable-macos-media-player' '--disable-wasapi' '--disable-ios-gl' '--disable-macos-touchbar' '--disable-macos-cocoa-cb' '--disable-tvos' '--disable-egl-angle-win32' '--bashdir=/usr/share/bash-completion/completions' '--zshdir=/usr/share/zsh/site-functions' '--disable-build-date' 'configure'
```

### Actual behavior

```
Checking for Raspberry Pi support                                         : yes 
Checking for EGL 1.4                                                      : Traceback (most recent call last):
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 118, in waf_entry_point
    run_commands()
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 178, in run_commands
    ctx=run_command(cmd_name)
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 169, in run_command
    ctx.execute()
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/wscript", line 965, in configure
    ctx.parse_dependencies(video_output_features)
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Configure.py", line 174, in fun
    return f(*k,**kw)
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/waftools/dependencies.py", line 160, in parse_dependencies
    [__check_dependency__(ctx, dependency) for dependency in dependencies]
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/waftools/dependencies.py", line 160, in <listcomp>
    [__check_dependency__(ctx, dependency) for dependency in dependencies]
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/waftools/dependencies.py", line 155, in __check_dependency__
    Dependency(ctx,
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/waftools/dependencies.py", line 47, in check
    self.check_autodetect_func()
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/waftools/dependencies.py", line 76, in check_autodetect_func
    if self.attributes['func'](self.ctx, self.identifier):
  File "/var/tmp/portage/media-video/mpv-0.33.1-r1/work/mpv-0.33.1/waftools/checks/custom.py", line 146, in fn
    if not minVersionSV or ctx.egl_provider_version and \
AttributeError: 'cctx' object has no attribute 'egl_provider_version'
```

### Log file

[build.log.gz](https://github.com/mpv-player/mpv/files/7180616/build.log.gz)

**Comment by cyph84** [comment]
Perhaps you can add --disable-egl to your waf configure?

**Comment by CounterPillow** [comment]
You can still leave this open, waf shouldn't crash in this case. There's clearly a problem in our build system.

**Comment by Dudemanguy** [comment]
This hasn't really been fixed technically, but for rpi especially you should build with meson these days. waf is full of mysterious bugs regarding rpi that nobody is going to fix (one day we'll remove this). Closing in light of that.
