### ISSUE TITLE
Waf script fail when install

### ISSUE THREAD

**Issue by sl1pkn07** [mpv-player/mpv#9547]
### mpv version and platform versions

d86bfebe6d

archlinux ([AUR] `mpv-build-git` package) https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mpv-build-git

### Reproduction steps

clone mpv-build repo and the dependencies (ffmpeg,libass, and mpv iself)
run  `mpv/bootstrap.py` script
set the build options in the `ffmpeg_options`and `mpv-options` file
build the project with the `build` script
and run the ìnstall` script 

### Expected behavior

install ok

### Actual behavior

fail install

### Log file

~~~
Waf: Leaving directory `/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/build'
Build failed
Traceback (most recent call last):
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Task.py", line 180, in process
    ret=self.run()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Build.py", line 554, in run
    x.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 188, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
waflib.Errors.WafError: Could not create the directory /tmp/makepkg/mpv-build-git/pkg/mpv-build-git/usr --confdir=/etc/mpv --htmldir=/usr/share/doc/mpv/html --disable-build-date --lua=luajit --enable-cdda --enable-dvbin --enable-dvdnav --enable-html-build --enable-libarchive --enable-libmpv-shared --enable-openal --enable-sdl2 --enable-shaderc --enable-vulkan --enable-gl-x11 --enable-egl --enable-egl-x11 --enable-egl-drm --enable-gl-wayland --enable-drm --enable-gbm --enable-wayland-scanner --enable-wayland-protocols --enable-wayland --enable-vdpau --enable-vdpau-gl-x11 --enable-vaapi --enable-vaapi-x11 --enable-vaapi-wayland --enable-vaapi-drm --enable-vaapi-x-egl --enable-cuda-hwaccel --enable-cuda-interop --color=yes

Traceback (most recent call last):
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Task.py", line 180, in process
    ret=self.run()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Build.py", line 554, in run
    x.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 188, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
waflib.Errors.WafError: Could not create the directory /tmp/makepkg/mpv-build-git/pkg/mpv-build-git/usr --confdir=/etc/mpv --htmldir=/usr/share/doc/mpv/html --disable-build-date --lua=luajit --enable-cdda --enable-dvbin --enable-dvdnav --enable-html-build --enable-libarchive --enable-libmpv-shared --enable-openal --enable-sdl2 --enable-shaderc --enable-vulkan --enable-gl-x11 --enable-egl --enable-egl-x11 --enable-egl-drm --enable-gl-wayland --enable-drm --enable-gbm --enable-wayland-scanner --enable-wayland-protocols --enable-wayland --enable-vdpau --enable-vdpau-gl-x11 --enable-vaapi --enable-vaapi-x11 --enable-vaapi-wayland --enable-vaapi-drm --enable-vaapi-x-egl --enable-cuda-hwaccel --enable-cuda-interop --color=yes

Traceback (most recent call last):
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Task.py", line 180, in process
    ret=self.run()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Build.py", line 554, in run
    x.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 188, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
waflib.Errors.WafError: Could not create the directory /tmp/makepkg/mpv-build-git/pkg/mpv-build-git/usr --confdir=/etc/mpv --htmldir=/usr/share/doc/mpv/html --disable-build-date --lua=luajit --enable-cdda --enable-dvbin --enable-dvdnav --enable-html-build --enable-libarchive --enable-libmpv-shared --enable-openal --enable-sdl2 --enable-shaderc --enable-vulkan --enable-gl-x11 --enable-egl --enable-egl-x11 --enable-egl-drm --enable-gl-wayland --enable-drm --enable-gbm --enable-wayland-scanner --enable-wayland-protocols --enable-wayland --enable-vdpau --enable-vdpau-gl-x11 --enable-vaapi --enable-vaapi-x11 --enable-vaapi-wayland --enable-vaapi-drm --enable-vaapi-x-egl --enable-cuda-hwaccel --enable-cuda-interop --color=yes

Traceback (most recent call last):
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Task.py", line 180, in process
    ret=self.run()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Build.py", line 554, in run
    x.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 188, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
waflib.Errors.WafError: Could not create the directory /tmp/makepkg/mpv-build-git/pkg/mpv-build-git/usr --confdir=/etc/mpv --htmldir=/usr/share/doc/mpv/html --disable-build-date --lua=luajit --enable-cdda --enable-dvbin --enable-dvdnav --enable-html-build --enable-libarchive --enable-libmpv-shared --enable-openal --enable-sdl2 --enable-shaderc --enable-vulkan --enable-gl-x11 --enable-egl --enable-egl-x11 --enable-egl-drm --enable-gl-wayland --enable-drm --enable-gbm --enable-wayland-scanner --enable-wayland-protocols --enable-wayland --enable-vdpau --enable-vdpau-gl-x11 --enable-vaapi --enable-vaapi-x11 --enable-vaapi-wayland --enable-vaapi-drm --enable-vaapi-x-egl --enable-cuda-hwaccel --enable-cuda-interop --color=yes

Traceback (most recent call last):
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Task.py", line 180, in process
    ret=self.run()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Build.py", line 554, in run
    x.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 188, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
waflib.Errors.WafError: Could not create the directory /tmp/makepkg/mpv-build-git/pkg/mpv-build-git/usr --confdir=/etc/mpv --htmldir=/usr/share/doc/mpv/html --disable-build-date --lua=luajit --enable-cdda --enable-dvbin --enable-dvdnav --enable-html-build --enable-libarchive --enable-libmpv-shared --enable-openal --enable-sdl2 --enable-shaderc --enable-vulkan --enable-gl-x11 --enable-egl --enable-egl-x11 --enable-egl-drm --enable-gl-wayland --enable-drm --enable-gbm --enable-wayland-scanner --enable-wayland-protocols --enable-wayland --enable-vdpau --enable-vdpau-gl-x11 --enable-vaapi --enable-vaapi-x11 --enable-vaapi-wayland --enable-vaapi-drm --enable-vaapi-x-egl --enable-cuda-hwaccel --enable-cuda-interop --color=yes

Traceback (most recent call last):
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Task.py", line 180, in process
    ret=self.run()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Build.py", line 554, in run
    x.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 188, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
waflib.Errors.WafError: Could not create the directory /tmp/makepkg/mpv-build-git/pkg/mpv-build-git/usr --confdir=/etc/mpv --htmldir=/usr/share/doc/mpv/html --disable-build-date --lua=luajit --enable-cdda --enable-dvbin --enable-dvdnav --enable-html-build --enable-libarchive --enable-libmpv-shared --enable-openal --enable-sdl2 --enable-shaderc --enable-vulkan --enable-gl-x11 --enable-egl --enable-egl-x11 --enable-egl-drm --enable-gl-wayland --enable-drm --enable-gbm --enable-wayland-scanner --enable-wayland-protocols --enable-wayland --enable-vdpau --enable-vdpau-gl-x11 --enable-vaapi --enable-vaapi-x11 --enable-vaapi-wayland --enable-vaapi-drm --enable-vaapi-x-egl --enable-cuda-hwaccel --enable-cuda-interop --color=yes

Traceback (most recent call last):
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Task.py", line 180, in process
    ret=self.run()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Build.py", line 554, in run
    x.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 179, in mkdir
    self.parent.mkdir()
  File "/tmp/makepkg/mpv-build-git/src/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/Node.py", line 188, in mkdir
    raise Errors.WafError('Could not create the directory %r'%self)
waflib.Errors.WafError: Could not create the directory /tmp/makepkg/mpv-build-git/pkg/mpv-build-git/usr --confdir=/etc/mpv --htmldir=/usr/share/doc/mpv/html --disable-build-date --lua=luajit --enable-cdda --enable-dvbin --enable-dvdnav --enable-html-build --enable-libarchive --enable-libmpv-shared --enable-openal --enable-sdl2 --enable-shaderc --enable-vulkan --enable-gl-x11 --enable-egl --enable-egl-x11 --enable-egl-drm --enable-gl-wayland --enable-drm --enable-gbm --enable-wayland-scanner --enable-wayland-protocols --enable-wayland --enable-vdpau --enable-vdpau-gl-x11 --enable-vaapi --enable-vaapi-x11 --enable-vaapi-wayland --enable-vaapi-drm --enable-vaapi-x-egl --enable-cuda-hwaccel --enable-cuda-interop --color=yes

~~~

python 3.9.9

not use meson due a lack of support in the mpv-build scripts

greetings

**Comment by avih** [comment]
The NAME_options file handling was modified recently.

It was always documented to use one argument per line, but until now it also worked with multiple arguments per line, and now only one per line works.

See the updated README file and use one argument per line.

**Comment by sl1pkn07** [comment]
ok. done 
tnx
