### ISSUE TITLE
Does libmpv support stream recording?

### ISSUE THREAD

**Issue by silvioprog** [mpv-player/mpv#9625]
Hi.

Is it possible to record a stream using libmpv? I have the following Python code using the [python-mpv](https://github.com/jaseg/python-mpv) library, that is a libmpv binding:

```bash
# libmpv version: 1.109.0
```

```python
import mpv

player = mpv.MPV()
player.play('http://s1.myradiostream.com:12508/listen.mp3')
player.command('set_property_string', 'stream_record', '/home/user/record.mp3')
player.wait_for_playback()
```

however, when I try to run it, got the following error:

```bash
$ python main.py 
Traceback (most recent call last):
  File "/home/user/main.py", line 5, in <module>
    player.command('set_property_string', 'stream_record', '/home/user/record.mp3')
  File "/home/user/venv/lib/python3.10/site-packages/mpv.py", line 1041, in command
    _mpv_command(self.handle, (c_char_p*len(args))(*args))
  File "/home/user/venv/lib/python3.10/site-packages/mpv.py", line 133, in raise_for_ec
    raise ex(ec, *args)
ValueError: ('Invalid value for mpv parameter', -4, (<MpvHandle object at 0x7fe21caefa40>, <mpv.c_char_p_Array_4 object at 0x7fe21c800040>))
```

So, does libmpv support stream recording?

TIA for any help!

**Comment by dfaker** [comment]
Your two options for this are passing the keyword argument to the constructor:

```
import mpv

player = mpv.MPV(stream_record='out.mp3')
player.play('http://s1.myradiostream.com:12508/listen.mp3')
player.wait_for_playback()
```

or setting the property on MPV before playback:

```
import mpv

player = mpv.MPV()
player.stream_record='out.mp3'
player.play('http://s1.myradiostream.com:12508/listen.mp3')
player.wait_for_playback()
```

**Comment by silvioprog** [comment]
@dfaker, thanks a lot for this information, it worked and will help a lot! 🤩
