### ISSUE TITLE
Wrong handling of Darwin versions 21 and greater

### ISSUE THREAD

**Issue by ryandesign** [mpv-player/mpv#9907]
I've deleted the issue template because it is not applicable.

waftools/detections/compiler_swift.py contains:

```
                build_version = '10.' + str(major) + '.' + str(minor)
                # from 20 onwards macOS 11.0 starts
                if int(version_parts.group(1)) >= 20:
                    build_version = '11.' + str(minor)
```

So, it treats Darwin versions 20 and later as macOS 11.

This is wrong for Darwin 21 and later. Darwin 21 is macOS 12, Darwin 22 is expected to be macOS 13 next year, and so forth.

**Comment by ryandesign** [comment]
Because of this, I suspect, this is how it currently fails to build on macOS 12 x86_64:

```
Checking for macOS SDK                   : Traceback (most recent call last):
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/.waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/.waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/.waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/.waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/.waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/.waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/wscript", line 955, in configure
    ctx.load('detections.compiler_swift')
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/.waf3-2.0.23-7dbdd0b348178777c338c9a31f6218a5/waflib/Configure.py", line 156, in load
    func(self)
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/waftools/detections/compiler_swift.py", line 201, in configure
    __find_macos_sdk(ctx)
  File "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_multimedia_mpv/mpv/work/mpv-player-mpv-df6d84c/waftools/detections/compiler_swift.py", line 158, in __find_macos_sdk
    minor = string.ascii_lowercase.index(version_parts.group(2).lower())
ValueError: substring not found
```

Full log [here](https://build.macports.org/builders/ports-12_x86_64-builder/builds/22397/steps/install-port/logs/stdio).

**Comment by Akemi** [comment]
btw, the issue template is not applicable because you picked the wrong one. the right one would have been the build one.

see PR #9885. yes this is known. since none knew what the new scheme would be when macOS 11 was released. the strides of the minor versions are 2 apparently (up from 1), which also needs to be changed.

the error though seems unrelated to that. since it's a few lines above the one mentioned.

```
minor = string.ascii_lowercase.index(version_parts.group(2).lower())
```

the error in your second comment is related to #8939.
