### ISSUE TITLE
mpv causing anki crashed?

### ISSUE THREAD

**Issue by Stallion-X** [mpv-player/mpv#9922]
anki: https://github.com/ankitects/anki
There's no response when I opening the program.(latest anki-2.1.49-windows)
And when I opened anki-console.exe, I found these:

AttributeError: ’ MpvManager’ object has no attribute ’_sock’
Exception in thread Thread-100:
mpv timed out, restarting
Traceback (most recent call last):
File "threading, py", line 932, in _bootstrap_inner
File "threading, py", line 870, in run
File "aqt\mpv. py", line 234, in _reader
AttributeError: ’MpvManager’ object has no attribute ’_sock’
Exception in thread Thread-101:
mpv timed out, restarting
Traceback (most recent call last):
File "threading, py", line 932, in _bootstrap_inner
File "threading, py", line 870, in run
File "aqt\mpv. py", line 234, in _reader
AttributeError: ’MpvManager’ object has no attribute ’_sock’
Exception in thread Thread-102:
mpv timed out, restarting

An infinite loop about mpv? I have no idea...

**Comment by LaserEyess** [comment]
This is an anki bug.

**Comment by Stallion-X** [comment]
> This is an anki bug.

People in the Anki forums told me to use mplayer instead of mpv, so I‘m thinking of reporting this to the mpv issues...

**Comment by LaserEyess** [comment]
The error, specifically, is: ` AttributeError: ’MpvManager’ object has no attribute ’_sock’`. That's not code inside mpv, it's python code in anki. It really has nothing to do with this project, and if you want it fixed you need to report it to anki.

**Comment by Stallion-X** [comment]
> The error, specifically, is: ` AttributeError: ’MpvManager’ object has no attribute ’_sock’`. That's not code inside mpv, it's python code in anki. It really has nothing to do with this project, and if you want it fixed you need to report it to anki.
> 
> Also, if you want help with mpv, you need to fill out the issue template which you completely ignored.

ok thx for helping
